/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks
#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg;
typedef struct tyTuple__VFMuwODWfhYGyNy8SKacJQ tyTuple__VFMuwODWfhYGyNy8SKacJQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TType__ovu87YsUa1ANGt6vVxQTnw tyObject_TType__ovu87YsUa1ANGt6vVxQTnw;
typedef struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ;
typedef struct tyObject_TSym__28oQRSX37sWj59aavVTxbUA tyObject_TSym__28oQRSX37sWj59aavVTxbUA;
typedef struct tyObject_TIdent__un9ccjtt539bmsw80XV2co0w tyObject_TIdent__un9ccjtt539bmsw80XV2co0w;
typedef struct tySequence__7A69ci2GuL2dj4UKdKtVyqw tySequence__7A69ci2GuL2dj4UKdKtVyqw;
typedef struct tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyObject_Time__JgJH6jx9a1sQSuMyj9cRAtvg tyObject_Time__JgJH6jx9a1sQSuMyj9cRAtvg;
typedef struct tyObject_TCtx__AlxnyWOhOUdc9booScgfH5w tyObject_TCtx__AlxnyWOhOUdc9booScgfH5w;
typedef struct tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag;
typedef struct tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ;
typedef struct tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ;
typedef struct tyObject_IdentCachecolonObjectType___GI9caWHRPvWH1UWYHnXk9a4g tyObject_IdentCachecolonObjectType___GI9caWHRPvWH1UWYHnXk9a4g;
typedef struct tyObject_TPassContext__0JbJCKLAoGySUSatjZl9aTA tyObject_TPassContext__0JbJCKLAoGySUSatjZl9aTA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_IdGeneratorcolonObjectType___KEA9bhczjIlMNahOEvdo2DA tyObject_IdGeneratorcolonObjectType___KEA9bhczjIlMNahOEvdo2DA;
typedef struct tySequence__YdLNCDKYeipzJx3I8Xw82Q tySequence__YdLNCDKYeipzJx3I8Xw82Q;
typedef struct tySequence__YdLNCDKYeipzJx3I8Xw82Q_Content tySequence__YdLNCDKYeipzJx3I8Xw82Q_Content;
typedef struct tySequence__NIc7wNjmUakD3gTMf7CMxw tySequence__NIc7wNjmUakD3gTMf7CMxw;
typedef struct tySequence__NIc7wNjmUakD3gTMf7CMxw_Content tySequence__NIc7wNjmUakD3gTMf7CMxw_Content;
typedef struct tyObject_TNodeTable__08rF6ZpdgO8lzDwO81oNEw tyObject_TNodeTable__08rF6ZpdgO8lzDwO81oNEw;
typedef struct tySequence__TaWjlC4YvDPojR6zt4uXZA tySequence__TaWjlC4YvDPojR6zt4uXZA;
typedef struct tySequence__TaWjlC4YvDPojR6zt4uXZA_Content tySequence__TaWjlC4YvDPojR6zt4uXZA_Content;
typedef struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ tySequence__3OLAdPZ6N0PKLmvrN88SKQ;
typedef struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content;
typedef struct tyObject_PProccolonObjectType___OH45umLJUXskBGaF6tL2TQ tyObject_PProccolonObjectType___OH45umLJUXskBGaF6tL2TQ;
typedef struct tySequence__XlqMZDxTtcOJELx9bQzmlXA tySequence__XlqMZDxTtcOJELx9bQzmlXA;
typedef struct tySequence__XlqMZDxTtcOJELx9bQzmlXA_Content tySequence__XlqMZDxTtcOJELx9bQzmlXA_Content;
typedef struct tyObject_Table__jdaj3ueNdw23w7TkQv4fWw tyObject_Table__jdaj3ueNdw23w7TkQv4fWw;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ;
typedef struct tyObject_ModuleGraphcolonObjectType___cj79b3ee01o9b9clpMt6mtDQA tyObject_ModuleGraphcolonObjectType___cj79b3ee01o9b9clpMt6mtDQA;
typedef struct tyObject_Profiler__II0hbXkSZ1RnD2T35UnODA tyObject_Profiler__II0hbXkSZ1RnD2T35UnODA;
typedef struct tyObject_TStackFrame__SyoAuk89cOJ4tDtbP0QJy5Q tyObject_TStackFrame__SyoAuk89cOJ4tDtbP0QJy5Q;
typedef struct tySequence__05u3LpqxtZ3GVWLKEifOYQ tySequence__05u3LpqxtZ3GVWLKEifOYQ;
typedef struct tySequence__05u3LpqxtZ3GVWLKEifOYQ_Content tySequence__05u3LpqxtZ3GVWLKEifOYQ_Content;
typedef struct tyObject_Table__9awAD2Gxpy9asoU9aybLQvMbg tyObject_Table__9awAD2Gxpy9asoU9aybLQvMbg;
typedef struct tySequence__E8pi9b5QNahsURYzXMjh3qw tySequence__E8pi9b5QNahsURYzXMjh3qw;
typedef struct tySequence__E8pi9b5QNahsURYzXMjh3qw_Content tySequence__E8pi9b5QNahsURYzXMjh3qw_Content;
typedef struct tyObject_PackedSet__hRuUdZjflZIXRNAtmAzbGg tyObject_PackedSet__hRuUdZjflZIXRNAtmAzbGg;
typedef struct tyObject_TrunkcolonObjectType___PBvJ8FiP69afU5ssG4nKHxw tyObject_TrunkcolonObjectType___PBvJ8FiP69afU5ssG4nKHxw;
typedef struct tySequence__fFPUc3Img7I0LE1pNf30tw tySequence__fFPUc3Img7I0LE1pNf30tw;
typedef struct tySequence__fFPUc3Img7I0LE1pNf30tw_Content tySequence__fFPUc3Img7I0LE1pNf30tw_Content;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_TNodePair__LayVkATuCSNOdQMGEoP9abg tyObject_TNodePair__LayVkATuCSNOdQMGEoP9abg;
typedef struct tyObject_VmArgs__LJ5Oj2oOL7ouaAXu29b04bA tyObject_VmArgs__LJ5Oj2oOL7ouaAXu29b04bA;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__UwPE9c85etCw9aDwVb5qrduA tyTuple__UwPE9c85etCw9aDwVb5qrduA;
typedef struct tyTuple__47w2DboNEPf69aPgubZdd7Q tyTuple__47w2DboNEPf69aPgubZdd7Q;
typedef struct tyObject_TFullReg__L9c2dSs9cMozAitJdvxRARug tyObject_TFullReg__L9c2dSs9cMozAitJdvxRARug;
typedef NU8 tyEnum_PathComponent__wuLP2yUPe0lAU0NArPbn5g;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__VFMuwODWfhYGyNy8SKacJQ {
	tyEnum_PathComponent__wuLP2yUPe0lAU0NArPbn5g Field0;
	NimStringV2 Field1;
};
struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU32 tySet_tyEnum_TNodeFlag__n19aX3s10J0sOzf6pZLMnrQ;
typedef NU8 tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ;
struct tySequence__7A69ci2GuL2dj4UKdKtVyqw {
	NI len;
	tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content* p;
};
struct tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg {
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* typField;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info;
	tySet_tyEnum_TNodeFlag__n19aX3s10J0sOzf6pZLMnrQ flags;
	tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind;
union{
	struct {
	NI64 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* sym;
} _kind_4;
	struct {
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* ident;
} _kind_5;
	struct {
	tySequence__7A69ci2GuL2dj4UKdKtVyqw sons;
} _kind_6;
};
};
typedef tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* tyArray__hX9c9cqaVtrzDxOqdHkvJlqA[1];
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
typedef NU8 tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw;
typedef NU8 tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw;
struct tyObject_Time__JgJH6jx9a1sQSuMyj9cRAtvg {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag {
	NI32 module;
	NI32 item;
};
typedef NU8 tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA;
typedef NU16 tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ;
typedef NU64 tySet_tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA;
typedef NU32 tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg;
typedef NU8 tyEnum_TLocKind__nciik9bCjoRABm4xUHiJPlw;
typedef NU8 tyEnum_TStorageLoc__jZPJ57twA9bABh0WS23o5Xg;
typedef NU16 tySet_tyEnum_TLocFlag__0Lja9bAGXZMPYu5yFiOM5Cg;
struct tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ {
	tyEnum_TLocKind__nciik9bCjoRABm4xUHiJPlw k;
	tyEnum_TStorageLoc__jZPJ57twA9bABh0WS23o5Xg storage;
	tySet_tyEnum_TLocFlag__0Lja9bAGXZMPYu5yFiOM5Cg flags;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* lode;
	NimStringV2 snippet;
};
struct tyObject_TSym__28oQRSX37sWj59aavVTxbUA {
	tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag itemId;
	tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA kind;
union{
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* gcUnsafetyReason;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* transformedBody;
} _kind_1;
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* guard;
	NI bitsize;
	NI alignment;
} _kind_2;
};
	tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ magic;
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* typ;
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* name;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* ownerField;
	tySet_tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA flags;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* ast;
	tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg options;
	NI position;
	NI32 offset;
	NI32 disamb;
	tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ loc;
	tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ* annex;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* constraint;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* instantiatedFrom;
};
struct tyObject_TIdent__un9ccjtt539bmsw80XV2co0w {
	NI id;
	NimStringV2 s;
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* next;
	NI h;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_TPassContext__0JbJCKLAoGySUSatjZl9aTA {
	RootObj Sup;
	tyObject_IdGeneratorcolonObjectType___KEA9bhczjIlMNahOEvdo2DA* idgen;
};
struct tySequence__YdLNCDKYeipzJx3I8Xw82Q {
	NI len;
	tySequence__YdLNCDKYeipzJx3I8Xw82Q_Content* p;
};
struct tySequence__NIc7wNjmUakD3gTMf7CMxw {
	NI len;
	tySequence__NIc7wNjmUakD3gTMf7CMxw_Content* p;
};
struct tySequence__TaWjlC4YvDPojR6zt4uXZA {
	NI len;
	tySequence__TaWjlC4YvDPojR6zt4uXZA_Content* p;
};
struct tyObject_TNodeTable__08rF6ZpdgO8lzDwO81oNEw {
	NI counter;
	tySequence__TaWjlC4YvDPojR6zt4uXZA data;
	NIM_BOOL ignoreTypes;
};
struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ {
	NI len;
	tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content* p;
};
typedef NU8 tyEnum_TEvalMode__YA9bZ7jlPuwcLmR9aAQ5AWNw;
typedef NU8 tySet_tyEnum_TSandboxFlag__6VI30bN48uRt7O8Hr89aMpQ;
struct tySequence__XlqMZDxTtcOJELx9bQzmlXA {
	NI len;
	tySequence__XlqMZDxTtcOJELx9bQzmlXA_Content* p;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
	NI len;
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct tyObject_Table__jdaj3ueNdw23w7TkQv4fWw {
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
	NI counter;
};
struct tyObject_Profiler__II0hbXkSZ1RnD2T35UnODA {
	NF tEnter;
	tyObject_TStackFrame__SyoAuk89cOJ4tDtbP0QJy5Q* tos;
};
struct tySequence__05u3LpqxtZ3GVWLKEifOYQ {
	NI len;
	tySequence__05u3LpqxtZ3GVWLKEifOYQ_Content* p;
};
struct tySequence__E8pi9b5QNahsURYzXMjh3qw {
	NI len;
	tySequence__E8pi9b5QNahsURYzXMjh3qw_Content* p;
};
struct tyObject_Table__9awAD2Gxpy9asoU9aybLQvMbg {
	tySequence__E8pi9b5QNahsURYzXMjh3qw data;
	NI counter;
};
struct tySequence__fFPUc3Img7I0LE1pNf30tw {
	NI len;
	tySequence__fFPUc3Img7I0LE1pNf30tw_Content* p;
};
typedef NI tyArray__emiAJ8okywrJw7ZHLzlXbQ[34];
struct tyObject_PackedSet__hRuUdZjflZIXRNAtmAzbGg {
	NI elems;
	NI counter;
	NI max;
	tyObject_TrunkcolonObjectType___PBvJ8FiP69afU5ssG4nKHxw* head;
	tySequence__fFPUc3Img7I0LE1pNf30tw data;
	tyArray__emiAJ8okywrJw7ZHLzlXbQ a;
};
struct tyObject_TCtx__AlxnyWOhOUdc9booScgfH5w {
	tyObject_TPassContext__0JbJCKLAoGySUSatjZl9aTA Sup;
	tySequence__YdLNCDKYeipzJx3I8Xw82Q code;
	tySequence__NIc7wNjmUakD3gTMf7CMxw debug;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* globals;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* constants;
	tyObject_TNodeTable__08rF6ZpdgO8lzDwO81oNEw contstantTab;
	tySequence__3OLAdPZ6N0PKLmvrN88SKQ types;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* currentExceptionA;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* currentExceptionB;
	NI exceptionInstr;
	tyObject_PProccolonObjectType___OH45umLJUXskBGaF6tL2TQ* prc;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* module;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* callsite;
	tyEnum_TEvalMode__YA9bZ7jlPuwcLmR9aAQ5AWNw mode;
	tySet_tyEnum_TSandboxFlag__6VI30bN48uRt7O8Hr89aMpQ features;
	NIM_BOOL traceActive;
	NI loopIterations;
	NI callDepth;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ comesFromHeuristic;
	tySequence__XlqMZDxTtcOJELx9bQzmlXA callbacks;
	tyObject_Table__jdaj3ueNdw23w7TkQv4fWw callbackIndex;
	NimStringV2 errorFlag;
	tyObject_IdentCachecolonObjectType___GI9caWHRPvWH1UWYHnXk9a4g* cache;
	tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* config;
	tyObject_ModuleGraphcolonObjectType___cj79b3ee01o9b9clpMt6mtDQA* graph;
	NI oldErrorCount;
	tyObject_Profiler__II0hbXkSZ1RnD2T35UnODA profiler;
	NI* templInstCounter;
	tySequence__05u3LpqxtZ3GVWLKEifOYQ vmstateDiff;
	tyObject_Table__9awAD2Gxpy9asoU9aybLQvMbg procToCodePos;
	NIM_BOOL cannotEval;
	tyObject_PackedSet__hRuUdZjflZIXRNAtmAzbGg locals;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
	NI len;
	tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content {
	NI cap;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* data[SEQ_DECL_SIZE];
};
struct tySequence__YdLNCDKYeipzJx3I8Xw82Q_Content {
	NI cap;
	NU64 data[SEQ_DECL_SIZE];
};
struct tySequence__NIc7wNjmUakD3gTMf7CMxw_Content {
	NI cap;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ data[SEQ_DECL_SIZE];
};
struct tyObject_TNodePair__LayVkATuCSNOdQMGEoP9abg {
	NI h;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* key;
	NI val;
};
struct tySequence__TaWjlC4YvDPojR6zt4uXZA_Content {
	NI cap;
	tyObject_TNodePair__LayVkATuCSNOdQMGEoP9abg data[SEQ_DECL_SIZE];
};
struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content {
	NI cap;
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(tyObject_VmArgs__LJ5Oj2oOL7ouaAXu29b04bA* args_p0, void* ClE_0);
	void* ClE_0;
} tyProc__ISPqYSqS0bRSsVXU8r9bvKg;
struct tySequence__XlqMZDxTtcOJELx9bQzmlXA_Content {
	NI cap;
	tyProc__ISPqYSqS0bRSsVXU8r9bvKg data[SEQ_DECL_SIZE];
};
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
	NI Field0;
	NimStringV2 Field1;
	NI Field2;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content {
	NI cap;
	tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tyTuple__UwPE9c85etCw9aDwVb5qrduA {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* Field0;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* Field1;
};
struct tySequence__05u3LpqxtZ3GVWLKEifOYQ_Content {
	NI cap;
	tyTuple__UwPE9c85etCw9aDwVb5qrduA data[SEQ_DECL_SIZE];
};
struct tyTuple__47w2DboNEPf69aPgubZdd7Q {
	NI Field0;
	NI Field1;
	NI Field2;
};
struct tySequence__E8pi9b5QNahsURYzXMjh3qw_Content {
	NI cap;
	tyTuple__47w2DboNEPf69aPgubZdd7Q data[SEQ_DECL_SIZE];
};
struct tySequence__fFPUc3Img7I0LE1pNf30tw_Content {
	NI cap;
	tyObject_TrunkcolonObjectType___PBvJ8FiP69afU5ssG4nKHxw* data[SEQ_DECL_SIZE];
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content {
	NI cap;
	tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tyObject_VmArgs__LJ5Oj2oOL7ouaAXu29b04bA {
	NI ra;
	NI rb;
	NI rc;
	tyObject_TFullReg__L9c2dSs9cMozAitJdvxRARug* slots;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* currentException;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ currentLineInfo;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newTree__ast_u4171)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** children_p1, NI children_p1Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__ast_u3216)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* father_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* son_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13144)(tyEnum_PathComponent__wuLP2yUPe0lAU0NArPbn5g a_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newIntNode__ast_u5201)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_p0, NI64 intVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3253)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13152)(NimStringV2 a_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newStrNode__ast_u5423)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_p0, NimStringV2 strVal_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13306)(NI a_p0);
static N_INLINE(NI, safeLen__ast_u3198)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
static N_INLINE(NI, len__ast_u3191)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3256)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** dest_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newNode__ast_u4070)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newSymNode__ast_u5172)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* sym_p0, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__28oQRSX37sWj59aavVTxbUA*, lookupInRecord__astalgo_u30)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* field_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TIdent__un9ccjtt539bmsw80XV2co0w*, getIdent__idents_u206)(tyObject_IdentCachecolonObjectType___GI9caWHRPvWH1UWYHnXk9a4g* ic_p0, NimStringV2 identifier_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vmconv_u39)(NI64 a_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u4575)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___idents_u155)(tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vmconv_u47)(NI a_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u14141)(tyTuple__UV3llMMYFckfui8YMBuUZA* a_p0);
static const struct {
	NI cap;
	NIM_CHAR data[8];
} TM__Cx3HKQVn9adIHIP3IGqzKvw_2 = {(7 | NIM_STRLIT_FLAG), "seconds"};
static const NimStringV2 TM__Cx3HKQVn9adIHIP3IGqzKvw_3 = {7, ((NimStrPayload*) (&TM__Cx3HKQVn9adIHIP3IGqzKvw_2))};
static const struct {
	NI cap;
	NIM_CHAR data[11];
} TM__Cx3HKQVn9adIHIP3IGqzKvw_4 = {(10 | NIM_STRLIT_FLAG), "nanosecond"};
static const NimStringV2 TM__Cx3HKQVn9adIHIP3IGqzKvw_5 = {10, ((NimStrPayload*) (&TM__Cx3HKQVn9adIHIP3IGqzKvw_4))};
extern NIM_BOOL nimInErrorMode__system_u4206;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}

static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4206));
	return result;
}

static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimSetMem__systemZmemory_u7(p_p0, ((int) 0), size_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13144)(tyEnum_PathComponent__wuLP2yUPe0lAU0NArPbn5g a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newIntNode__ast_u5201(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 6), ((NI64) (a_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13152)(NimStringV2 a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newStrNode__ast_u5423(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 20), a_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13134)(tyTuple__VFMuwODWfhYGyNy8SKacJQ a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyArray__hX9c9cqaVtrzDxOqdHkvJlqA T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
nimZeroMem(((void*) T1_), sizeof(tyArray__hX9c9cqaVtrzDxOqdHkvJlqA));
result = newTree__ast_u4171(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 160), T1_, 0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
if ((!(NIM_TRUE))) {
	goto LA4_;
}
colontmpD_ = NIM_NIL;
colontmpD_ = toLit__vm_u13144(a_p0.Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__2;
if ((!(NIM_TRUE))) {
	goto LA8_;
}
colontmpD__2 = NIM_NIL;
colontmpD__2 = toLit__vm_u13152(a_p0.Field1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA8_: ;
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13306)(NI a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newIntNode__ast_u5201(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 6), ((NI64) (a_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13293)(tyTuple__XOVT24GHXwqiEj5GCsEGCA a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyArray__hX9c9cqaVtrzDxOqdHkvJlqA T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
nimZeroMem(((void*) T1_), sizeof(tyArray__hX9c9cqaVtrzDxOqdHkvJlqA));
result = newTree__ast_u4171(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 160), T1_, 0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
if ((!(NIM_TRUE))) {
	goto LA4_;
}
colontmpD_ = NIM_NIL;
colontmpD_ = toLit__vm_u13152(a_p0.Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__2;
if ((!(NIM_TRUE))) {
	goto LA8_;
}
colontmpD__2 = NIM_NIL;
colontmpD__2 = toLit__vm_u13306(a_p0.Field1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA8_: ;
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(NI, len__ast_u3191)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NI result;
NI T1_;
T1_ = (*n_p0)._kind_6.sons.len;
result = T1_;
	return result;
}

static N_INLINE(NI, safeLen__ast_u3198)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NI result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NI) 0);
{
	if ((!((((*n_p0).kind >= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0)) && ((*n_p0).kind <= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 23)))))) {
	goto LA3_;
}
result = ((NI) 0);
}
goto LA1_;
LA3_: ;
{
	result = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA1_: ;
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw, fromLit__vm_u13928)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* a_p0) {
	tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&result))), sizeof(tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw));
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* ai_1;
ai_1 = NIM_NIL;
{
	NI i_1;
NI colontmp_;
NI i_2;
i_1 = ((NI) 0);
colontmp_ = ((NI) 0);
colontmp_ = safeLen__ast_u3198(a_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
i_2 = ((NI) 0);
{
	while (1) {
	if ((!((i_2 < colontmp_)))) {
	goto LA4;
}
i_1 = i_2;
eqcopy___ast_u3256((&ai_1), ((*a_p0)._kind_6.sons).p->data[i_1]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
result |= (((NU8) 1) << (((tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw) ((*ai_1)._kind_1.intVal)) & 7));
i_2 += ((NI) 1);
}
LA4: ;
}
}
eqdestroy___ast_u3253(ai_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u13992)(tyTuple__XOVT24GHXwqiEj5GCsEGCA a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyArray__hX9c9cqaVtrzDxOqdHkvJlqA T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
nimZeroMem(((void*) T1_), sizeof(tyArray__hX9c9cqaVtrzDxOqdHkvJlqA));
result = newTree__ast_u4171(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 160), T1_, 0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
if ((!(NIM_TRUE))) {
	goto LA4_;
}
colontmpD_ = NIM_NIL;
colontmpD_ = toLit__vm_u13152(a_p0.Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__2;
if ((!(NIM_TRUE))) {
	goto LA8_;
}
colontmpD__2 = NIM_NIL;
colontmpD__2 = toLit__vm_u13306(a_p0.Field1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA8_: ;
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vmconv_u39)(NI64 a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newIntNode__ast_u5201(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 6), ((NI64) (a_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vmconv_u47)(NI a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newIntNode__ast_u5201(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 6), ((NI64) (a_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toTimeLit__vmconv_u29)(tyObject_Time__JgJH6jx9a1sQSuMyj9cRAtvg a_p0, tyObject_TCtx__AlxnyWOhOUdc9booScgfH5w* c_p1, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* obj_p2, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p3) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
tyArray__hX9c9cqaVtrzDxOqdHkvJlqA T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
colontmpD_ = NIM_NIL;
nimZeroMem(((void*) T1_), sizeof(tyArray__hX9c9cqaVtrzDxOqdHkvJlqA));
result = newTree__ast_u4171(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 38), T1_, 0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD_ = newNode__ast_u4070(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* reti_1;
tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* colontmpD__2;
tyObject_TSym__28oQRSX37sWj59aavVTxbUA* colontmpD__3;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__4;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__5;
if ((!(NIM_TRUE))) {
	goto LA4_;
}
reti_1 = NIM_NIL;
colontmpD__2 = NIM_NIL;
colontmpD__3 = NIM_NIL;
colontmpD__4 = NIM_NIL;
colontmpD__5 = NIM_NIL;
reti_1 = newNode__ast_u4070(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 34));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__2 = getIdent__idents_u206((*c_p1).cache, TM__Cx3HKQVn9adIHIP3IGqzKvw_3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__3 = lookupInRecord__astalgo_u30(obj_p2, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__4 = newSymNode__ast_u5172(colontmpD__3, info_p3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(reti_1, colontmpD__4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__5 = toLit__vmconv_u39(a_p0.seconds);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(reti_1, colontmpD__5);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, reti_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__5);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u4575(colontmpD__3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___idents_u155(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(reti_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* reti_2;
tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* colontmpD__6;
tyObject_TSym__28oQRSX37sWj59aavVTxbUA* colontmpD__7;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__8;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__9;
if ((!(NIM_TRUE))) {
	goto LA8_;
}
reti_2 = NIM_NIL;
colontmpD__6 = NIM_NIL;
colontmpD__7 = NIM_NIL;
colontmpD__8 = NIM_NIL;
colontmpD__9 = NIM_NIL;
reti_2 = newNode__ast_u4070(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 34));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__6 = getIdent__idents_u206((*c_p1).cache, TM__Cx3HKQVn9adIHIP3IGqzKvw_5);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__7 = lookupInRecord__astalgo_u30(obj_p2, colontmpD__6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__8 = newSymNode__ast_u5172(colontmpD__7, info_p3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(reti_2, colontmpD__8);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmpD__9 = toLit__vmconv_u47(a_p0.nanosecond);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(reti_2, colontmpD__9);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, reti_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__9);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__8);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u4575(colontmpD__7);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___idents_u155(colontmpD__6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(reti_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA8_: ;
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u14141)(tyTuple__UV3llMMYFckfui8YMBuUZA* a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyArray__hX9c9cqaVtrzDxOqdHkvJlqA T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
nimZeroMem(((void*) T1_), sizeof(tyArray__hX9c9cqaVtrzDxOqdHkvJlqA));
result = newTree__ast_u4171(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 160), T1_, 0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
if ((!(NIM_TRUE))) {
	goto LA4_;
}
colontmpD_ = NIM_NIL;
colontmpD_ = toLit__vm_u13152((*a_p0).Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__2;
if ((!(NIM_TRUE))) {
	goto LA8_;
}
colontmpD__2 = NIM_NIL;
colontmpD__2 = toLit__vm_u13152((*a_p0).Field1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___ast_u3253(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA8_: ;
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, toLit__vm_u14129)(tySequence__4eQHGndY6XBYpFOH09apV8Q a_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newNode__ast_u4070(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 41));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	tyTuple__UV3llMMYFckfui8YMBuUZA* ai_1;
NI i_1;
NI L_1;
NI T2_;
ai_1 = ((tyTuple__UV3llMMYFckfui8YMBuUZA*) 0);
i_1 = ((NI) 0);
T2_ = a_p0.len;
L_1 = T2_;
{
	while (1) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
if ((!((i_1 < L_1)))) {
	goto LA4;
}
colontmpD_ = NIM_NIL;
ai_1 = ((&(a_p0).p->data[i_1]));
colontmpD_ = toLit__vm_u14141(((&(*ai_1))));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
add__ast_u3216(result, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
i_1 += ((NI) 1);
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4: ;
}
}
}
	BeforeRet_: ;
		return result;
}

