/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 32
#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__5sqIMptsyAfPn3c9cPj4DOA)(NI16* pathName_p0);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw)(void);
typedef N_STDCALL_PTR(NI32, tyProc__aOhJuXP2rSFzW5eC9bSzvwg)(NI16* lpFileName_p0, NI32 dwFileAttributes_p1);
typedef NU8 tySet_tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ;
typedef NU8 tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ;
typedef N_STDCALL_PTR(NI32, tyProc__29cQilB9cqahn5yPQZH66TkA)(NI16* lpExistingFileName_p0, NI16* lpNewFileName_p1, NI32 bFailIfExists_p2);
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg, newWideCString__stdZwidestrs_u325)(NimStringV2 s_p0);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg a_p0);
static N_INLINE(NI, countBits32)(NU32 n_p0);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0);
N_CDECL(int, __builtin_popcount)(unsigned int x_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u239)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u123)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u126)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZprivateZoscommon_u72)(tyTuple__UV3llMMYFckfui8YMBuUZA x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2624)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tryMoveFSObject__stdZprivateZoscommon_u62)(NimStringV2 source_p0, NimStringV2 dest_p1, NIM_BOOL isDir_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u10)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0);
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ options_p2, NI bufferSize_p3);
static const struct {
	NI cap;
	NIM_CHAR data[109];
} TM__CMIme9a8i2wZOUbxErcFpJA_2 = {(108 | NIM_STRLIT_FLAG), "osfiles.nim(213, 3) `card(copyFlagSymlink * options) == 1` There should be exactly one cfSymlink* in options"};
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_3 = {108, ((NimStrPayload*) (&TM__CMIme9a8i2wZOUbxErcFpJA_2))};
static const struct {
	NI cap;
	NIM_CHAR data[12];
} TM__CMIme9a8i2wZOUbxErcFpJA_4 = {(11 | NIM_STRLIT_FLAG), "unreachable"};
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_5 = {11, ((NimStrPayload*) (&TM__CMIme9a8i2wZOUbxErcFpJA_4))};
extern NIM_BOOL nimInErrorMode__system_u4211;
extern tyProc__5sqIMptsyAfPn3c9cPj4DOA Dl_1442841195_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_1442840747_;
extern tyProc__aOhJuXP2rSFzW5eC9bSzvwg Dl_1442840842_;
extern tyProc__29cQilB9cqahn5yPQZH66TkA Dl_1442840845_;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}

static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4211));
	return result;
}

static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimSetMem__systemZmemory_u7(p_p0, ((int) 0), size_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg x_p0) {
	NI16* result;
result = x_p0.data;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0) {
	NIM_BOOL result;
tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg f_1;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&f_1))), sizeof(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg));
result = NIM_TRUE;
f_1 = newWideCString__stdZwidestrs_u325(file_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	NI16* T3_;
NI32 T4_;
NI32 err_1;
T3_ = ((NI16*) 0);
T3_ = toWideCString__stdZwidestrs_u49(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T4_ = ((NI32) 0);
T4_ = Dl_1442841195_(T3_);
if ((!((T4_ == ((NI32) 0))))) {
	goto LA5_;
}
result = NIM_FALSE;
err_1 = Dl_1442840747_();
{
	NIM_BOOL T9_;
T9_ = ((NIM_BOOL) 0);
T9_ = (err_1 == ((NI32) 2));
if (T9_) {
	goto LA10_;
}
T9_ = (err_1 == ((NI32) 3));
LA10_: ;
if ((!(T9_))) {
	goto LA11_;
}
result = NIM_TRUE;
}
goto LA7_;
LA11_: ;
{
	NIM_BOOL T14_;
NIM_BOOL T15_;
NI16* T17_;
NI32 T18_;
NI16* T20_;
NI32 T21_;
T14_ = ((NIM_BOOL) 0);
T15_ = ((NIM_BOOL) 0);
T15_ = (err_1 == ((NI32) 5));
if ((!(T15_))) {
	goto LA16_;
}
T17_ = ((NI16*) 0);
T17_ = toWideCString__stdZwidestrs_u49(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T18_ = ((NI32) 0);
T18_ = Dl_1442840842_(T17_, ((NI32) 128));
T15_ = (!((T18_ == ((NI32) 0))));
LA16_: ;
T14_ = T15_;
if ((!(T14_))) {
	goto LA19_;
}
T20_ = ((NI16*) 0);
T20_ = toWideCString__stdZwidestrs_u49(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T21_ = ((NI32) 0);
T21_ = Dl_1442841195_(T20_);
T14_ = (!((T21_ == ((NI32) 0))));
LA19_: ;
if ((!(T14_))) {
	goto LA22_;
}
result = NIM_TRUE;
}
goto LA7_;
LA22_: ;
LA7_: ;
}
LA5_: ;
eqdestroy___stdZwidestrs_u7(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0) {
	NI result;
NU32 x_2;
int T1_;
result = ((NI) 0);
x_2 = x_p0;
T1_ = ((int) 0);
T1_ = __builtin_popcount(((unsigned int) (x_2)));
result = ((NI) (T1_));
	return result;
}

static N_INLINE(NI, countBits32)(NU32 n_p0) {
	NI result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NI) 0);
result = countSetBitsImpl__systemZcountbits95impl_u26(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ options_p2, NI bufferSize_p3) {
	tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg s_1;
tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg d_1;
NIM_BOOL isSymlink_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&s_1))), sizeof(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg));
nimZeroMem(((void*) ((&d_1))), sizeof(tyObject_WideCStringObj__Y4mbfz4JpRWlVii9b3ufnsg));
{
	if ((!((!((countBits32((7 & options_p2)) == ((NI) 1))))))) {
	goto LA4_;
}
failedAssertImpl__stdZassertions_u239(TM__CMIme9a8i2wZOUbxErcFpJA_3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA4_: ;
isSymlink_1 = nossymlinkExists(source_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	NIM_BOOL T8_;
NIM_BOOL T10_;
T8_ = ((NIM_BOOL) 0);
T8_ = isSymlink_1;
if ((!(T8_))) {
	goto LA9_;
}
T10_ = ((NIM_BOOL) 0);
T10_ = ((options_p2 & (((NU8) 1) << (((NU) ((tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ) 2)) & 7U))) != 0);
if (T10_) {
	goto LA11_;
}
T10_ = NIM_TRUE;
LA11_: ;
T8_ = T10_;
LA9_: ;
if ((!(T8_))) {
	goto LA12_;
}
eqdestroy___stdZwidestrs_u7(d_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___stdZwidestrs_u7(s_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA12_: ;
s_1 = newWideCString__stdZwidestrs_u325(source_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
d_1 = newWideCString__stdZwidestrs_u325(dest_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	NI16* T16_;
NI16* T17_;
NI32 T18_;
NimStringV2 colontmpD_;
NI32 T22_;
tyTuple__UV3llMMYFckfui8YMBuUZA T23_;
T16_ = ((NI16*) 0);
T16_ = toWideCString__stdZwidestrs_u49(s_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
T17_ = ((NI16*) 0);
T17_ = toWideCString__stdZwidestrs_u49(d_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
T18_ = ((NI32) 0);
T18_ = Dl_1442840845_(T16_, T17_, ((NI32) 0));
if ((!((T18_ == ((NI32) 0))))) {
	goto LA19_;
}
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
T22_ = ((NI32) 0);
T22_ = osLastError__stdZoserrors_u126();
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA21_;
}
T23_.Field0 = source_p0;
T23_.Field1 = dest_p1;
colontmpD_ = dollar___stdZprivateZoscommon_u72(T23_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA21_;
}
raiseOSError__stdZoserrors_u123(T22_, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA21_;
}
{
	LA21_: ;
}
{
	eqdestroy___system_u2624(colontmpD_);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA19_: ;
{
	LA1_: ;
}
{
	oldNimErrFin1_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___stdZwidestrs_u7(d_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqdestroy___stdZwidestrs_u7(s_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin1_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, nosmoveFile)(NimStringV2 source_p0, NimStringV2 dest_p1) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = tryMoveFSObject__stdZprivateZoscommon_u62(source_p0, dest_p1, NIM_FALSE);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!((!(T3_))))) {
	goto LA4_;
}
raiseAssert__stdZassertions_u10(TM__CMIme9a8i2wZOUbxErcFpJA_5);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringV2 file_p0) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
{
	NIM_BOOL T3_;
NI32 T6_;
T3_ = ((NIM_BOOL) 0);
T3_ = nostryRemoveFile(file_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!((!(T3_))))) {
	goto LA4_;
}
T6_ = ((NI32) 0);
T6_ = osLastError__stdZoserrors_u126();
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
raiseOSError__stdZoserrors_u123(T6_, file_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA4_: ;
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, copyFileWithPermissions__stdZprivateZosfiles_u288)(NimStringV2 source_p0, NimStringV2 dest_p1, NIM_BOOL ignorePermissionErrors_p2, tySet_tyEnum_CopyFlag__0NBaDnO2bhUUFII9bwPD6LQ options_p3) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
noscopyFile(source_p0, dest_p1, options_p3, ((NI) 16384));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

