/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 64
#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ;
typedef struct tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ;
typedef struct tyObject_Target__w19a9beIvR3ojF569aWOKHcQA tyObject_Target__w19a9beIvR3ojF569aWOKHcQA;
typedef struct tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw;
typedef struct tyObject_MsgConfig__tg9cJUljlDsodA8lQ4uvrJA tyObject_MsgConfig__tg9cJUljlDsodA8lQ4uvrJA;
typedef struct tySequence__3G9bVnjEz0Hg26mp6JamL6A tySequence__3G9bVnjEz0Hg26mp6JamL6A;
typedef struct tySequence__3G9bVnjEz0Hg26mp6JamL6A_Content tySequence__3G9bVnjEz0Hg26mp6JamL6A_Content;
typedef struct tyObject_Table__8MQp4PaBjLC7O7g17l9bX3g tyObject_Table__8MQp4PaBjLC7O7g17l9bX3g;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw tySequence__7lEisrXlQEzwtUKW5pzRCw;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content tySequence__7lEisrXlQEzwtUKW5pzRCw_Content;
typedef struct tySequence__y6Ci6GE1ig6yoEa29bPNcCQ tySequence__y6Ci6GE1ig6yoEa29bPNcCQ;
typedef struct tySequence__y6Ci6GE1ig6yoEa29bPNcCQ_Content tySequence__y6Ci6GE1ig6yoEa29bPNcCQ_Content;
typedef struct tyObject_HashSet__BU9cPHn5sjDeM1qf2cbOU7Q tyObject_HashSet__BU9cPHn5sjDeM1qf2cbOU7Q;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__WWFb2jAutNhRCGvhjAqCbw tySequence__WWFb2jAutNhRCGvhjAqCbw;
typedef struct tySequence__WWFb2jAutNhRCGvhjAqCbw_Content tySequence__WWFb2jAutNhRCGvhjAqCbw_Content;
typedef struct tyObject_SuggestcolonObjectType___1iX9aFE0QV9buVfTyKKjZe4w tyObject_SuggestcolonObjectType___1iX9aFE0QV9buVfTyKKjZe4w;
typedef struct tyObject_ProfileDatacolonObjectType___KLIn8ic1TKwFhJA9b8FaMCw tyObject_ProfileDatacolonObjectType___KLIn8ic1TKwFhJA9b8FaMCw;
typedef struct tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ;
typedef struct tyObject_HSlice__ITk4fx5j9b0q1zogcnnFSGg tyObject_HSlice__ITk4fx5j9b0q1zogcnnFSGg;
typedef struct Exception Exception;
typedef struct tySequence__cTyVHeHOWk5jStsToosJ8Q tySequence__cTyVHeHOWk5jStsToosJ8Q;
typedef struct tySequence__cTyVHeHOWk5jStsToosJ8Q_Content tySequence__cTyVHeHOWk5jStsToosJ8Q_Content;
typedef struct tyTuple__ql3C7YNDGrqQ2MB7lxf3xg tyTuple__ql3C7YNDGrqQ2MB7lxf3xg;
typedef struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw tyTuple__xYhUhS7X82rKTqbT9bRfCnw;
typedef struct tyObject_TFileInfo__QQEkwUyXFx635gqK9bRBLLg tyObject_TFileInfo__QQEkwUyXFx635gqK9bRBLLg;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Cfile__mBCCe4uzoFnd5UHnz6U9b8w tyObject_Cfile__mBCCe4uzoFnd5UHnz6U9b8w;
typedef struct tyObject_StackTraceEntry__PH5g2qROCBvTfywgopkw3Q tyObject_StackTraceEntry__PH5g2qROCBvTfywgopkw3Q;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
typedef NU8 tyArray__YtcvxHNKV4YiecPE9ap1mcA[20];
typedef NU8 tyEnum_TBackend__c2XhG73YK9af3F2AQ9abHBGg;
typedef NU8 tyEnum_TSystemCPU__f9alh7nh0nfJv3YfQIujQPA;
typedef NU8 tyEnum_TSystemOS__Jx9bXn49att4eX9almlm9cXJ4g;
struct tyObject_Target__w19a9beIvR3ojF569aWOKHcQA {
	tyEnum_TSystemCPU__f9alh7nh0nfJv3YfQIujQPA targetCPU;
	tyEnum_TSystemCPU__f9alh7nh0nfJv3YfQIujQPA hostCPU;
	tyEnum_TSystemOS__Jx9bXn49att4eX9almlm9cXJ4g targetOS;
	tyEnum_TSystemOS__Jx9bXn49att4eX9almlm9cXJ4g hostOS;
	NI intSize;
	NI floatSize;
	NI ptrSize;
	NimStringV2 tnl;
};
typedef NU32 tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg;
typedef NU64 tySet_tyEnum_TGlobalOption__9co31xj9cK8swFW3sVOOTUOQ;
typedef NU8 tySet_tyEnum_TErrorOutput__BsBHL8SVTWQr8ETZnFFH8g;
struct tySequence__3G9bVnjEz0Hg26mp6JamL6A {
	NI len;
	tySequence__3G9bVnjEz0Hg26mp6JamL6A_Content* p;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw {
	NI len;
	tySequence__7lEisrXlQEzwtUKW5pzRCw_Content* p;
};
struct tyObject_Table__8MQp4PaBjLC7O7g17l9bX3g {
	tySequence__7lEisrXlQEzwtUKW5pzRCw data;
	NI counter;
};
struct tySequence__y6Ci6GE1ig6yoEa29bPNcCQ {
	NI len;
	tySequence__y6Ci6GE1ig6yoEa29bPNcCQ_Content* p;
};
struct tyObject_MsgConfig__tg9cJUljlDsodA8lQ4uvrJA {
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ trackPos;
	NIM_BOOL trackPosAttached;
	tySet_tyEnum_TErrorOutput__BsBHL8SVTWQr8ETZnFFH8g errorOutputs;
	tySequence__3G9bVnjEz0Hg26mp6JamL6A msgContext;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ lastError;
	tyObject_Table__8MQp4PaBjLC7O7g17l9bX3g filenameToIndexTbl;
	tySequence__y6Ci6GE1ig6yoEa29bPNcCQ fileInfos;
	NI32 systemFileIdx;
};
typedef NU8 tyEnum_FilenameOption__AbfpyQIkCAHJIn5AwapDsQ;
typedef NU8 tyEnum_Command__65vaQrd4zS7driWCx9aIGUA;
typedef NU8 tyEnum_TGCMode__YKwcrjaz9bwqMzsFQDehxdg;
typedef NU8 tyEnum_ExceptionSystem__FVnv6ql7bJpo1v5LceUFCA;
typedef NU8 tyEnum_SymbolFilesOption__nNmLA2VwxrYNex8Fy39bhEw;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
	NI len;
	tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__BU9cPHn5sjDeM1qf2cbOU7Q {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
typedef NU32 tySet_tyEnum_Feature__WAOtb850b8dLwhCPHZIK6Q;
typedef NU8 tySet_tyEnum_LegacyFeature__5V4QNek9aL1k5NEf9bPOK7Og;
typedef NU8 tyEnum_IdeCmd__XBhI2a6MSTdQPvJ7ukYZTg;
typedef NU8 tyEnum_TSystemCC__ERGMIn55Ar0U80dsl8Gq3g;
typedef NU8 tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw[13];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
	NI len;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyEnum_StdOrrKind__N43t7A9avNpKMdu7coJw5LA;
struct tySequence__WWFb2jAutNhRCGvhjAqCbw {
	NI len;
	tySequence__WWFb2jAutNhRCGvhjAqCbw_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(tyObject_SuggestcolonObjectType___1iX9aFE0QV9buVfTyKKjZe4w* result_p0, void* ClE_0);
	void* ClE_0;
} tyProc__Y9bRUqDhAUHMnTF1EoN6XDw;
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(NimStringV2 output_p0, void* ClE_0);
	void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
typedef NU8 tyEnum_Severity__TaEFrYtJUB0dJOdyA1BQFg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* config_p0, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p1, NimStringV2 msg_p2, tyEnum_Severity__TaEFrYtJUB0dJOdyA1BQFg severity_p3, void* ClE_0);
	void* ClE_0;
} tyProc__0CIN5gkvEgIPwGKkW9aApxQ;
struct tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ {
	tyEnum_TBackend__c2XhG73YK9af3F2AQ9abHBGg backend;
	tyObject_Target__w19a9beIvR3ojF569aWOKHcQA target;
	NI linesCompiled;
	tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg options;
	tySet_tyEnum_TGlobalOption__9co31xj9cK8swFW3sVOOTUOQ globalOptions;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* macrosToExpand;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* arcToExpand;
	tyObject_MsgConfig__tg9cJUljlDsodA8lQ4uvrJA m;
	tyEnum_FilenameOption__AbfpyQIkCAHJIn5AwapDsQ filenameOption;
	NimStringV2 unitSep;
	NI evalTemplateCounter;
	NI evalMacroCounter;
	NI8 exitcode;
	tyEnum_Command__65vaQrd4zS7driWCx9aIGUA cmd;
	NimStringV2 cmdInput;
	NIM_BOOL projectIsCmd;
	NIM_BOOL implicitCmd;
	tyEnum_TGCMode__YKwcrjaz9bwqMzsFQDehxdg selectedGC;
	tyEnum_ExceptionSystem__FVnv6ql7bJpo1v5LceUFCA exc;
	NIM_BOOL hintProcessingDots;
	NI verbosity;
	NI numberOfProcessors;
	NF lastCmdTime;
	tyEnum_SymbolFilesOption__nNmLA2VwxrYNex8Fy39bhEw symbolFiles;
	NI spellSuggestMax;
	tyObject_HashSet__BU9cPHn5sjDeM1qf2cbOU7Q cppDefines;
	NimStringV2 headerFile;
	NimStringV2 nimbasePattern;
	tySet_tyEnum_Feature__WAOtb850b8dLwhCPHZIK6Q features;
	tySet_tyEnum_LegacyFeature__5V4QNek9aL1k5NEf9bPOK7Og legacyFeatures;
	NimStringV2 arguments;
	tyEnum_IdeCmd__XBhI2a6MSTdQPvJ7ukYZTg ideCmd;
	tyEnum_TSystemCC__ERGMIn55Ar0U80dsl8Gq3g cCompiler;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw modifiedyNotes;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw cmdlineNotes;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw foreignPackageNotes;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw notes;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw warningAsErrors;
	tySet_tyEnum_TMsgKind__J6YRuV88Fn8HafnN79baROw mainPackageNotes;
	NI mainPackageId;
	NI errorCounter;
	NI hintCounter;
	NI warnCounter;
	NI errorMax;
	NI maxLoopIterationsVM;
	NI maxCallDepthVM;
	NIM_BOOL isVmTrace;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* configVars;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* symbols;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* packageCache;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimblePaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ searchPaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lazyPaths;
	NimStringV2 outFile;
	NimStringV2 outDir;
	NimStringV2 jsonBuildFile;
	NimStringV2 prefixDir;
	NimStringV2 libpath;
	NimStringV2 nimcacheDir;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* dllOverrides;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* moduleOverrides;
	tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* cfileSpecificOptions;
	NimStringV2 projectName;
	NimStringV2 projectPath;
	NimStringV2 projectFull;
	NIM_BOOL projectIsStdin;
	NimStringV2 stdinFile;
	tySet_tyEnum_StdOrrKind__N43t7A9avNpKMdu7coJw5LA lastMsgWasDot;
	NI32 projectMainIdx;
	NI32 projectMainIdx2;
	NimStringV2 command;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ commandArgs;
	NimStringV2 commandLine;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ extraCmds;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitImports;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitIncludes;
	NimStringV2 docSeeSrcUrl;
	NimStringV2 docRoot;
	NimStringV2 docCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ configFiles;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cIncludes;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLinkedLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ externalToLink;
	NimStringV2 linkOptionsCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ compileOptionsCmd;
	NimStringV2 linkOptions;
	NimStringV2 compileOptions;
	NimStringV2 cCompilerPath;
	tySequence__WWFb2jAutNhRCGvhjAqCbw toCompile;
	tyProc__Y9bRUqDhAUHMnTF1EoN6XDw suggestionResultHook;
	NI suggestVersion;
	NI suggestMaxResults;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ lastLineInfo;
	tyProc__k2HFjxisIgDALbEUFojxaQ writelnHook;
	tyProc__0CIN5gkvEgIPwGKkW9aApxQ structuredErrorHook;
	NimStringV2 cppCustomNamespace;
	NimStringV2 nimMainPrefix;
	tyObject_ProfileDatacolonObjectType___KLIn8ic1TKwFhJA9b8FaMCw* vmProfileData;
	NIM_BOOL expandProgress;
	NI expandLevels;
	NimStringV2 expandNodeResult;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ expandPosition;
	NimStringV2 currentConfigDir;
	NI clientProcessId;
};
typedef NU8 tyEnum_TGlobalOption__9co31xj9cK8swFW3sVOOTUOQ;
typedef NU8 tyEnum_FileMode__m6ZEz9b9czV5YJ5lg4IK9bc4Q;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw;
struct tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA {
	RootObj Sup;
	NI fProcessHandle;
	NI fThreadHandle;
	NI inHandle;
	NI outHandle;
	NI errHandle;
	NI id;
	tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* inStream;
	tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* outStream;
	tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* errStream;
	int exitStatus;
	NIM_BOOL exitFlag;
	tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw options;
};
typedef NimStringV2 tyArray__8ZvwQIddfpj2THRVPsFzIQ[1];
typedef N_NIMCALL_PTR(void, tyProc__iSHIdH3YKPbVylzN9a9agYWQ)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9aEu9cO7LzfVYXYlXhtzI5dg)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__FMBLKPr9bQhzrIFrj9ba7GJw)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__9cBK2FijRTJPg8u4i28iiWA)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__TFb6e4qvpv253z7vu0cxTw)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__ITk4fx5j9b0q1zogcnnFSGg slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__a05gzS0TpD9aw2b2ZGU4BbA)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__K9b9cKf6zvT73YqlJOkMvmyA)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__9aEXGns3hCn8ETlSMybXdjg)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ {
	RootObj Sup;
	tyProc__iSHIdH3YKPbVylzN9a9agYWQ closeImpl;
	tyProc__9aEu9cO7LzfVYXYlXhtzI5dg atEndImpl;
	tyProc__FMBLKPr9bQhzrIFrj9ba7GJw setPositionImpl;
	tyProc__9cBK2FijRTJPg8u4i28iiWA getPositionImpl;
	tyProc__TFb6e4qvpv253z7vu0cxTw readDataStrImpl;
	tyProc__a05gzS0TpD9aw2b2ZGU4BbA readLineImpl;
	tyProc__K9b9cKf6zvT73YqlJOkMvmyA readDataImpl;
	tyProc__K9b9cKf6zvT73YqlJOkMvmyA peekDataImpl;
	tyProc__9aEXGns3hCn8ETlSMybXdjg writeDataImpl;
	tyProc__iSHIdH3YKPbVylzN9a9agYWQ flushImpl;
};
struct tySequence__cTyVHeHOWk5jStsToosJ8Q {
	NI len;
	tySequence__cTyVHeHOWk5jStsToosJ8Q_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__cTyVHeHOWk5jStsToosJ8Q trace;
	Exception* up;
};
struct tyTuple__ql3C7YNDGrqQ2MB7lxf3xg {
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ Field0;
	NimStringV2 Field1;
};
struct tySequence__3G9bVnjEz0Hg26mp6JamL6A_Content {
	NI cap;
	tyTuple__ql3C7YNDGrqQ2MB7lxf3xg data[SEQ_DECL_SIZE];
};
struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw {
	NI Field0;
	NimStringV2 Field1;
	NI32 Field2;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content {
	NI cap;
	tyTuple__xYhUhS7X82rKTqbT9bRfCnw data[SEQ_DECL_SIZE];
};
struct tyObject_TFileInfo__QQEkwUyXFx635gqK9bRBLLg {
	NimStringV2 fullPath;
	NimStringV2 projPath;
	NimStringV2 shortName;
	NimStringV2 quotedName;
	NimStringV2 quotedFullName;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lines;
	NimStringV2 dirtyFile;
	NimStringV2 hash;
	NIM_BOOL dirty;
};
struct tySequence__y6Ci6GE1ig6yoEa29bPNcCQ_Content {
	NI cap;
	tyObject_TFileInfo__QQEkwUyXFx635gqK9bRBLLg data[SEQ_DECL_SIZE];
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content {
	NI cap;
	tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content {
	NI cap;
	NimStringV2 data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_CfileFlag__iV7y76hSmDEwn1bBV0fSzQ;
struct tyObject_Cfile__mBCCe4uzoFnd5UHnz6U9b8w {
	NimStringV2 nimname;
	NimStringV2 cname;
	NimStringV2 obj;
	tySet_tyEnum_CfileFlag__iV7y76hSmDEwn1bBV0fSzQ flags;
	NimStringV2 customArgs;
};
struct tySequence__WWFb2jAutNhRCGvhjAqCbw_Content {
	NI cap;
	tyObject_Cfile__mBCCe4uzoFnd5UHnz6U9b8w data[SEQ_DECL_SIZE];
};
struct tyObject_HSlice__ITk4fx5j9b0q1zogcnnFSGg {
	NI a;
	NI b;
};
struct tyObject_StackTraceEntry__PH5g2qROCBvTfywgopkw3Q {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__cTyVHeHOWk5jStsToosJ8Q_Content {
	NI cap;
	tyObject_StackTraceEntry__PH5g2qROCBvTfywgopkw3Q data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toFullPath__msgs_u605)(tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p0, NI32 fileIdx_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2621)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, secureHash__OOZdistZchecksumsZsrcZchecksumsZsha1_u865)(NIM_CHAR* str_p0, NI str_p0Len_0, tyArray__YtcvxHNKV4YiecPE9ap1mcA Result);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1724)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toGeneratedFile__options_u3814)(tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p0, NimStringV2 path_p1, NimStringV2 ext_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZdistZchecksumsZsrcZchecksumsZsha1_u935)(tyArray__YtcvxHNKV4YiecPE9ap1mcA self_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u536)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__m6ZEz9b9czV5YJ5lg4IK9bc4Q mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAll__stdZsyncio_u481)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZosproc_u1821)(tyTuple__XOVT24GHXwqiEj5GCsEGCA* dest_p0, tyTuple__XOVT24GHXwqiEj5GCsEGCA src_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u290)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2624)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA*, nospstartProcess)(NimStringV2 command_p0, NimStringV2 workingDir_p1, NimStringV2* args_p2, NI args_p2Len_0, tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw* env_p3, tySet_tyEnum_ProcessOption__9aCfVUyDFjLLn9an3vvc7WLw options_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u219)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u184)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ*, nospinputStream)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u673)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u58)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__XOVT24GHXwqiEj5GCsEGCA, readOutput__gorgeimpl_u10)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2633)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ*, nospoutputStream)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd__pureZstreams_u67)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__pureZstreams_u570)(tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nospwaitForExit)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0, NI timeout_p1);
N_LIB_PRIVATE N_NIMCALL(void, nospclose)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_u630)(NimStringV2 filename_p0, NimStringV2 content_p1);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_u7696)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2627)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZassertions_u19)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
static const struct {
	NI cap;
	NIM_CHAR data[1];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_2 = {(0 | NIM_STRLIT_FLAG), ""};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_3 = {0, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_2))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_4 = {(1 | NIM_STRLIT_FLAG), "\011"};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_5 = {1, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_4))};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_6 = {1, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_4))};
static const struct {
	NI cap;
	NIM_CHAR data[7];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_7 = {(6 | NIM_STRLIT_FLAG), "gorge_"};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_8 = {6, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_7))};
static const struct {
	NI cap;
	NIM_CHAR data[4];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_9 = {(3 | NIM_STRLIT_FLAG), "txt"};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_10 = {3, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_9))};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_11 = {0, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_2))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_12 = {(1 | NIM_STRLIT_FLAG), "\012"};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_13 = {1, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_12))};
static const struct {
	NI cap;
	NIM_CHAR data[29];
} TM__69a9b06YSkBJW7wqzuZfJ29aQ_14 = {(28 | NIM_STRLIT_FLAG), "Error running startProcess: "};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_15 = {28, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_14))};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_16 = {0, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_2))};
static const NimStringV2 TM__69a9b06YSkBJW7wqzuZfJ29aQ_17 = {28, ((NimStrPayload*) (&TM__69a9b06YSkBJW7wqzuZfJ29aQ_14))};
extern NIM_BOOL nimInErrorMode__system_u4211;
extern Exception* currException__system_u3917;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}

static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4211));
	return result;
}

static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimSetMem__systemZmemory_u7(p_p0, ((int) 0), size_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}

static N_INLINE(void, copyMem__system_u1724)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}

static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
	if ((!((((NI) 0) < src_p1.len)))) {
	goto LA3_;
}
copyMem__system_u1724(((void*) (((&(*(*dest_p0).p).data[(*dest_p0).len])))), ((void*) (((&(*src_p1.p).data[((NI) 0)])))), (src_p1.len));
(*dest_p0).len += src_p1.len;
(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple__XOVT24GHXwqiEj5GCsEGCA, readOutput__gorgeimpl_u10)(tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_p0) {
	tyTuple__XOVT24GHXwqiEj5GCsEGCA result;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* output_1;
NI T12_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&result))), sizeof(tyTuple__XOVT24GHXwqiEj5GCsEGCA));
output_1 = NIM_NIL;
eqsink___system_u2633(((&result.Field0)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_11);
output_1 = nospoutputStream(p_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	while (1) {
	NIM_BOOL T4_;
NimStringV2 colontmpD_;
T4_ = ((NIM_BOOL) 0);
T4_ = atEnd__pureZstreams_u67(output_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
if ((!((!(T4_))))) {
	goto LA3;
}
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
colontmpD_ = readLine__pureZstreams_u570(output_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA5_;
}
prepareAdd(((&result.Field0)), (0 + colontmpD_.len));
appendString(((&result.Field0)), colontmpD_);
prepareAdd(((&result.Field0)), 1);
appendString(((&result.Field0)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_13);
{
	LA5_: ;
}
{
	eqdestroy___system_u2624(colontmpD_);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA3: ;
}
{
	if ((!((((NI) 0) < result.Field0.len)))) {
	goto LA10_;
}
setLengthStrV2(((&result.Field0)), (((NI) (result.Field0.len - ((NI) 1)))));
}
LA10_: ;
T12_ = ((NI) 0);
T12_ = nospwaitForExit(p_p0, ((NI) -1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
result.Field1 = T12_;
{
	LA1_: ;
}
{
	eqdestroy___pureZstreams_u673(output_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
result = currException__system_u3917;
	return result;
}

static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
NIM_BOOL T1_;
T1_ = ((NIM_BOOL) 0);
T1_ = (targetDepth_p1 <= (*source_p0).depth);
if ((!(T1_))) {
	goto LA2_;
}
T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
result = T1_;
	return result;
}

static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_u7696)(void) {
	NimStringV2 result;
NimStringV2 T1_;
{
		result.len = 0;
result.p = NIM_NIL;
T1_.len = 0;
T1_.p = NIM_NIL;
{
	if ((!((currException__system_u3917 == ((Exception*) NIM_NIL))))) {
	goto LA4_;
}
result = TM__69a9b06YSkBJW7wqzuZfJ29aQ_16;
}
goto LA2_;
LA4_: ;
{
	eqcopy___system_u2627(((&result)), (*currException__system_u3917).message);
}
LA2_: ;
goto BeforeRet_;
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZassertions_u19((&currException__system_u3917), (*currException__system_u3917).up, NIM_FALSE);
}

N_LIB_PRIVATE N_NIMCALL(tyTuple__XOVT24GHXwqiEj5GCsEGCA, opGorge__gorgeimpl_u14)(NimStringV2 cmd_p0, NimStringV2 input_p1, NimStringV2 cache_p2, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p3, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p4) {
	tyTuple__XOVT24GHXwqiEj5GCsEGCA result;
NimStringV2 workingDir_1;
NimStringV2 colontmpD_;
NimStringV2 colontmp_;
NI colontmp__2;
NimStringV2 blitTmp_1;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&result))), sizeof(tyTuple__XOVT24GHXwqiEj5GCsEGCA));
workingDir_1.len = 0;
workingDir_1.p = NIM_NIL;
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
colontmp_.len = 0;
colontmp_.p = NIM_NIL;
colontmpD_ = toFullPath__msgs_u605(conf_p4, info_p3.fileIndex);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
workingDir_1 = nosparentDir(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
colontmp_ = TM__69a9b06YSkBJW7wqzuZfJ29aQ_3;
colontmp__2 = ((NI) 0);
blitTmp_1 = colontmp_;
eqwasMoved___system_u2621(((&colontmp_)));
result.Field0 = blitTmp_1;
result.Field1 = colontmp__2;
{
	NimStringV2 colontmpD__2;
NimStringV2 filename_1;
NimStringV2 colontmpD__3;
NimStringV2 colontmpD__4;
tyArray__YtcvxHNKV4YiecPE9ap1mcA h_1;
NimStringV2 T7_;
NimStringV2 T8_;
FILE* f_1;
NIM_BOOL readSuccessful_1;
tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_1;
tyArray__8ZvwQIddfpj2THRVPsFzIQ T21_;
tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* T22_;
tyTuple__XOVT24GHXwqiEj5GCsEGCA T32_;
if ((!((((NI) 0) < cache_p2.len)))) {
	goto LA4_;
}
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
filename_1.len = 0;
filename_1.p = NIM_NIL;
colontmpD__3.len = 0;
colontmpD__3.p = NIM_NIL;
colontmpD__4.len = 0;
colontmpD__4.p = NIM_NIL;
nimZeroMem(((void*) h_1), sizeof(tyArray__YtcvxHNKV4YiecPE9ap1mcA));
T7_.len = 0;
T7_.p = NIM_NIL;
T7_ = rawNewString((((2 + cmd_p0.len) + input_p1.len) + cache_p2.len));
appendString(((&T7_)), cmd_p0);
appendString(((&T7_)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_5);
appendString(((&T7_)), input_p1);
appendString(((&T7_)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_6);
appendString(((&T7_)), cache_p2);
colontmpD__2 = T7_;
secureHash__OOZdistZchecksumsZsrcZchecksumsZsha1_u865(((colontmpD__2).p ? (colontmpD__2).p->data : NIM_NIL), colontmpD__2.len, h_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
T8_.len = 0;
T8_.p = NIM_NIL;
colontmpD__3 = dollar___OOZdistZchecksumsZsrcZchecksumsZsha1_u935(h_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
T8_ = rawNewString((6 + colontmpD__3.len));
appendString(((&T8_)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_8);
appendString(((&T8_)), colontmpD__3);
colontmpD__4 = T8_;
filename_1 = toGeneratedFile__options_u3814(conf_p4, colontmpD__4, TM__69a9b06YSkBJW7wqzuZfJ29aQ_10);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
f_1 = 0;
{
	NIM_BOOL T11_;
NimStringV2 colontmp__3;
NI colontmp__4;
tyTuple__XOVT24GHXwqiEj5GCsEGCA T16_;
NimStringV2 blitTmp_2;
T11_ = ((NIM_BOOL) 0);
T11_ = (!((((*conf_p4).globalOptions & (((NU64) 1) << (((NU) ((tyEnum_TGlobalOption__9co31xj9cK8swFW3sVOOTUOQ) 1)) & 63U))) != 0)));
if ((!(T11_))) {
	goto LA12_;
}
T11_ = open__stdZsyncio_u536((&f_1), filename_1, ((tyEnum_FileMode__m6ZEz9b9czV5YJ5lg4IK9bc4Q) 0), ((NI) -1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
LA12_: ;
if ((!(T11_))) {
	goto LA13_;
}
colontmp__3.len = 0;
colontmp__3.p = NIM_NIL;
colontmp__3 = readAll__stdZsyncio_u481(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA15_;
}
colontmp__4 = ((NI) 0);
blitTmp_2 = colontmp__3;
eqwasMoved___system_u2621(((&colontmp__3)));
T16_.Field0 = blitTmp_2;
T16_.Field1 = colontmp__4;
eqsink___pureZosproc_u1821(((&result)), T16_);
close__stdZsyncio_u290(f_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA15_;
}
eqdestroy___system_u2624(colontmp__3);
eqdestroy___system_u2624(colontmpD__4);
eqdestroy___system_u2624(colontmpD__3);
eqdestroy___system_u2624(filename_1);
eqdestroy___system_u2624(colontmpD__2);
eqdestroy___system_u2624(colontmp_);
eqdestroy___system_u2624(colontmpD_);
eqdestroy___system_u2624(workingDir_1);
goto BeforeRet_;
{
	LA15_: ;
}
{
	eqdestroy___system_u2624(colontmp__3);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
}
LA13_: ;
readSuccessful_1 = NIM_FALSE;
p_1 = NIM_NIL;
T22_ = NIM_NIL;
T22_ = nospstartProcess(cmd_p0, workingDir_1, T21_, 0, ((tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw*) NIM_NIL), 12);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZosproc_u219(T22_);
	goto LA20_;
}
p_1 = T22_;
{
	tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* colontmpD__5;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* colontmpD__6;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* T28_;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* T29_;
if ((!((!((input_p1.len == ((NI) 0))))))) {
	goto LA25_;
}
colontmpD__5 = NIM_NIL;
colontmpD__6 = NIM_NIL;
T28_ = NIM_NIL;
T28_ = nospinputStream(p_1);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZstreams_u673(T28_);
	goto LA27_;
}
colontmpD__5 = T28_;
write__pureZstreams_u184(colontmpD__5, input_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA27_;
}
T29_ = NIM_NIL;
T29_ = nospinputStream(p_1);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZstreams_u673(T29_);
	goto LA27_;
}
colontmpD__6 = T29_;
close__pureZstreams_u58(colontmpD__6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA27_;
}
{
	LA27_: ;
}
{
	eqdestroy___pureZstreams_u673(colontmpD__6);
eqdestroy___pureZstreams_u673(colontmpD__5);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA20_;
}
}
LA25_: ;
T32_ = readOutput__gorgeimpl_u10(p_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA20_;
}
eqsink___pureZosproc_u1821(((&result)), T32_);
nospclose(p_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA20_;
}
readSuccessful_1 = NIM_TRUE;
{
	if ((!((result.Field1 == ((NI) 0))))) {
	goto LA35_;
}
writeFile__stdZsyncio_u630(filename_1, result.Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA20_;
}
}
LA35_: ;
{
	LA20_: ;
}
{
	eqdestroy___pureZosproc_u219(p_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA19_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	LA19_: ;
if ((isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1342458112) || isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 258371072))) {
	(*nimErr_) = NIM_FALSE;
{
	NimStringV2 colontmp__5;
NimStringV2 colontmpD__7;
NimStringV2 T46_;
NI colontmp__6;
tyTuple__XOVT24GHXwqiEj5GCsEGCA T47_;
NimStringV2 blitTmp_3;
if ((!((!(readSuccessful_1))))) {
	goto LA44_;
}
colontmp__5.len = 0;
colontmp__5.p = NIM_NIL;
colontmpD__7.len = 0;
colontmpD__7.p = NIM_NIL;
T46_.len = 0;
T46_.p = NIM_NIL;
colontmpD__7 = getCurrentExceptionMsg__system_u7696();
T46_ = rawNewString((28 + colontmpD__7.len));
appendString(((&T46_)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_15);
appendString(((&T46_)), colontmpD__7);
colontmp__5 = T46_;
colontmp__6 = ((NI) -1);
blitTmp_3 = colontmp__5;
T47_.Field0 = blitTmp_3;
T47_.Field1 = colontmp__6;
eqsink___pureZosproc_u1821(((&result)), T47_);
eqdestroy___system_u2624(colontmpD__7);
}
LA44_: ;
popCurrentException();
LA40_: ;
}
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
{
	LA6_: ;
}
{
	eqdestroy___system_u2624(colontmpD__4);
eqdestroy___system_u2624(colontmpD__3);
eqdestroy___system_u2624(filename_1);
eqdestroy___system_u2624(colontmpD__2);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
goto LA2_;
LA4_: ;
{
	tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* p_2;
tyArray__8ZvwQIddfpj2THRVPsFzIQ T53_;
tyObject_ProcessObj__nmbwhtRW8vPb4MWVUOiwqA* T54_;
tyTuple__XOVT24GHXwqiEj5GCsEGCA T64_;
p_2 = NIM_NIL;
T54_ = NIM_NIL;
T54_ = nospstartProcess(cmd_p0, workingDir_1, T53_, 0, ((tyObject_StringTableObj__0P3m7501aN2ol2UKnK1guw*) NIM_NIL), 12);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZosproc_u219(T54_);
	goto LA52_;
}
p_2 = T54_;
{
	tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* colontmpD__8;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* colontmpD__9;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* T60_;
tyObject_StreamObj__gmiHWVSRJ9cDJ5nm8mQy8oQ* T61_;
if ((!((!((input_p1.len == ((NI) 0))))))) {
	goto LA57_;
}
colontmpD__8 = NIM_NIL;
colontmpD__9 = NIM_NIL;
T60_ = NIM_NIL;
T60_ = nospinputStream(p_2);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZstreams_u673(T60_);
	goto LA59_;
}
colontmpD__8 = T60_;
write__pureZstreams_u184(colontmpD__8, input_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA59_;
}
T61_ = NIM_NIL;
T61_ = nospinputStream(p_2);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___pureZstreams_u673(T61_);
	goto LA59_;
}
colontmpD__9 = T61_;
close__pureZstreams_u58(colontmpD__9);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA59_;
}
{
	LA59_: ;
}
{
	eqdestroy___pureZstreams_u673(colontmpD__9);
eqdestroy___pureZstreams_u673(colontmpD__8);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA52_;
}
}
LA57_: ;
T64_ = readOutput__gorgeimpl_u10(p_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA52_;
}
eqsink___pureZosproc_u1821(((&result)), T64_);
nospclose(p_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA52_;
}
{
	LA52_: ;
}
{
	eqdestroy___pureZosproc_u219(p_2);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA51_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	LA51_: ;
if ((isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1342458112) || isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 258371072))) {
	NimStringV2 colontmp__7;
NimStringV2 colontmpD__10;
NimStringV2 T70_;
NI colontmp__8;
tyTuple__XOVT24GHXwqiEj5GCsEGCA T71_;
NimStringV2 blitTmp_4;
(*nimErr_) = NIM_FALSE;
colontmp__7.len = 0;
colontmp__7.p = NIM_NIL;
colontmpD__10.len = 0;
colontmpD__10.p = NIM_NIL;
T70_.len = 0;
T70_.p = NIM_NIL;
colontmpD__10 = getCurrentExceptionMsg__system_u7696();
T70_ = rawNewString((28 + colontmpD__10.len));
appendString(((&T70_)), TM__69a9b06YSkBJW7wqzuZfJ29aQ_17);
appendString(((&T70_)), colontmpD__10);
colontmp__7 = T70_;
colontmp__8 = ((NI) -1);
blitTmp_4 = colontmp__7;
T71_.Field0 = blitTmp_4;
T71_.Field1 = colontmp__8;
eqsink___pureZosproc_u1821(((&result)), T71_);
eqdestroy___system_u2624(colontmpD__10);
popCurrentException();
LA68_: ;
}
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA2_: ;
{
	LA1_: ;
}
{
	eqdestroy___system_u2624(colontmp_);
eqdestroy___system_u2624(colontmpD_);
eqdestroy___system_u2624(workingDir_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

