/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 64
#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TType__ovu87YsUa1ANGt6vVxQTnw tyObject_TType__ovu87YsUa1ANGt6vVxQTnw;
typedef struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ;
typedef struct tyObject_TSym__28oQRSX37sWj59aavVTxbUA tyObject_TSym__28oQRSX37sWj59aavVTxbUA;
typedef struct tyObject_TIdent__un9ccjtt539bmsw80XV2co0w tyObject_TIdent__un9ccjtt539bmsw80XV2co0w;
typedef struct tySequence__7A69ci2GuL2dj4UKdKtVyqw tySequence__7A69ci2GuL2dj4UKdKtVyqw;
typedef struct tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content;
typedef struct tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag;
typedef struct tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ;
typedef struct tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ;
typedef struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ tySequence__3OLAdPZ6N0PKLmvrN88SKQ;
typedef struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content;
typedef struct tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_BOOL tyArray__zl3qUQvo0CT9bJi9b5H7mRkw[65];
struct tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU32 tySet_tyEnum_TNodeFlag__n19aX3s10J0sOzf6pZLMnrQ;
typedef NU8 tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ;
struct tySequence__7A69ci2GuL2dj4UKdKtVyqw {
	NI len;
	tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content* p;
};
struct tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg {
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* typField;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info;
	tySet_tyEnum_TNodeFlag__n19aX3s10J0sOzf6pZLMnrQ flags;
	tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind;
union{
	struct {
	NI64 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* sym;
} _kind_4;
	struct {
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* ident;
} _kind_5;
	struct {
	tySequence__7A69ci2GuL2dj4UKdKtVyqw sons;
} _kind_6;
};
};
typedef NU8 tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA;
typedef NU8 tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA;
struct tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag {
	NI32 module;
	NI32 item;
};
typedef NU16 tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ;
typedef NU64 tySet_tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA;
typedef NU32 tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg;
typedef NU8 tyEnum_TLocKind__nciik9bCjoRABm4xUHiJPlw;
typedef NU8 tyEnum_TStorageLoc__jZPJ57twA9bABh0WS23o5Xg;
typedef NU16 tySet_tyEnum_TLocFlag__0Lja9bAGXZMPYu5yFiOM5Cg;
struct tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ {
	tyEnum_TLocKind__nciik9bCjoRABm4xUHiJPlw k;
	tyEnum_TStorageLoc__jZPJ57twA9bABh0WS23o5Xg storage;
	tySet_tyEnum_TLocFlag__0Lja9bAGXZMPYu5yFiOM5Cg flags;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* lode;
	NimStringV2 snippet;
};
struct tyObject_TSym__28oQRSX37sWj59aavVTxbUA {
	tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag itemId;
	tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA kind;
union{
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* gcUnsafetyReason;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* transformedBody;
} _kind_1;
	struct {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* guard;
	NI bitsize;
	NI alignment;
} _kind_2;
};
	tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ magic;
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* typ;
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* name;
	tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* ownerField;
	tySet_tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA flags;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* ast;
	tySet_tyEnum_TOption__9cfqdTKDMna3tPo6jl6pNlg options;
	NI position;
	NI32 offset;
	NI32 disamb;
	tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ loc;
	tyObject_TLib__guNNcX8lAHZRa6o9buCFEwQ* annex;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* constraint;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* instantiatedFrom;
};
typedef NU8 tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg;
typedef NU8 tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw;
typedef NU8 tyEnum_TCallingConvention__rpDZaDIcRXqWsChhzmOTSw;
typedef NU64 tySet_tyEnum_TTypeFlag__UNcNxdTtVtYv5xD3A2Q9cKg;
struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ {
	NI len;
	tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content* p;
};
struct tyObject_TType__ovu87YsUa1ANGt6vVxQTnw {
	tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag itemId;
	tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw kind;
	tyEnum_TCallingConvention__rpDZaDIcRXqWsChhzmOTSw callConv;
	tySet_tyEnum_TTypeFlag__UNcNxdTtVtYv5xD3A2Q9cKg flags;
	tySequence__3OLAdPZ6N0PKLmvrN88SKQ sons;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* ownerField;
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* sym;
	NI64 size;
	NI16 align;
	NI16 paddingAtEnd;
	tyObject_TLoc__plk21qHoX9azgXw4NCHGxUQ loc;
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* typeInst;
	tyObject_ItemId__5N9acCKognYgk5yCHR6Kr9ag uniqueId;
};
typedef NU8 tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA;
typedef NU8 tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw[9];
typedef NU8 tyEnum_TDistinctCompare__HvUI0ZaOBLbYMykJoTLm7Q;
typedef NU16 tySet_tyEnum_TTypeCmpFlag__tdd9b0fY4ENivWxyQMQG7uA;
typedef NU8 tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA;
typedef NU8 tyEnum_TTypeFlag__UNcNxdTtVtYv5xD3A2Q9cKg;
typedef NU8 tyEnum_TMsgKind__iz4UvM3kK9cv7Vr9cxzAlIGw;
typedef NU8 tyEnum_TErrorHandling__muRdtwJRTgC0pLAbV2ARkA;
typedef NU16 tySet_tyEnum_TRenderFlag__I3S1IuWfpw7AObGFigfGvA;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
	NimStringV2 Field0;
	NI Field1;
	NI Field2;
};
struct tyObject_TIdent__un9ccjtt539bmsw80XV2co0w {
	NI id;
	NimStringV2 s;
	tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* next;
	NI h;
};
typedef NU8 tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw;
struct tySequence__7A69ci2GuL2dj4UKdKtVyqw_Content {
	NI cap;
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* data[SEQ_DECL_SIZE];
};
struct tySequence__3OLAdPZ6N0PKLmvrN88SKQ_Content {
	NI cap;
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isAtom__ast_u7224)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg, isAssignable__parampatterns_u315)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* owner_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p1);
static N_INLINE(NIM_BOOL, dontInlineConstant__trees_u396)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* orig_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* cnst_p1);
static N_INLINE(NI, len__ast_u3191)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, astdef__ast_u4597)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_p0);
static N_INLINE(tyObject_TSym__28oQRSX37sWj59aavVTxbUA*, owner__ast_u6255)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u4578)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA** dest_p0, tyObject_TSym__28oQRSX37sWj59aavVTxbUA* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u4575)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*, skipTypes__ast_u5380)(tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* t_p0, tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw kinds_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3379)(tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3253)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, compareTypes__types_u2778)(tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* x_p0, tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* y_p1, tyEnum_TDistinctCompare__HvUI0ZaOBLbYMykJoTLm7Q cmp_p2, tySet_tyEnum_TTypeCmpFlag__tdd9b0fY4ENivWxyQMQG7uA flags_p3);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ, getMagic__trees_u122)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* op_p0);
static N_INLINE(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, lastSon__ast_u5209)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3256)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** dest_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* src_p1);
static N_INLINE(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg**, X5BX5D___ast_u5212)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(NI, safeLen__ast_u3198)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLentableBranch__parampatterns_u318)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* owner_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u10)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA, checkForSideEffects__parampatterns_u206)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0);
static N_INLINE(NIM_BOOL, isRoutine__ast_u7153)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, newNodeI__ast_u4092)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_p0, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2633)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, compileConstraints__parampatterns_u78)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* p_p0, NimStringV2* result_p1, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p2);
N_LIB_PRIVATE N_NIMCALL(void, patternError__parampatterns_u39)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p1);
N_LIB_PRIVATE N_NOINLINE(void, liMessage__msgs_u1223)(tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p0, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p1, tyEnum_TMsgKind__iz4UvM3kK9cv7Vr9cxzAlIGw msg_p2, NimStringV2 arg_p3, tyEnum_TErrorHandling__muRdtwJRTgC0pLAbV2ARkA eh_p4, tyTuple__kN8up2W6YKc5YA9avn5mV5w* info2_p5, NIM_BOOL isRaw_p6, NIM_BOOL ignoreError_p7);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1724)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderTree__renderer_u59)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, tySet_tyEnum_TRenderFlag__I3S1IuWfpw7AObGFigfGvA renderFlags_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2624)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___idents_u155)(tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___idents_u158)(tyObject_TIdent__un9ccjtt539bmsw80XV2co0w** dest_p0, tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* src_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1732)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(void, add__parampatterns_u42)(NimStringV2* code_p0, tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA op_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuNormalize)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringV2 s_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2373)(NimStringV2* s_p0);
static N_INLINE(NimStringV2, toFileLineCol__msgs_u701)(tyTuple__kN8up2W6YKc5YA9avn5mV5w* info_p0);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
N_LIB_PRIVATE N_NIMCALL(void, internalErrorImpl__msgs_u1594)(tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p0, tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ info_p1, NimStringV2 errMsg_p2, tyTuple__kN8up2W6YKc5YA9avn5mV5w* info2_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHumanStr__ast_u7575)(tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA kind_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___nodekinds_u168)(tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ e_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ast_u3262)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** dest_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* src_p1);
static NIM_CONST tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw TM__kdeXVhLeMhTeIyOxnAjnxA_2 = {
0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
, 0x00};
static NIM_CONST tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw TM__kdeXVhLeMhTeIyOxnAjnxA_3 = {
0x10, 0xa8, 0x00, 0x00, 0x00, 0x60, 0x80, 0x00
, 0x00};
static NIM_CONST tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw TM__kdeXVhLeMhTeIyOxnAjnxA_4 = {
0x10, 0xa8, 0xe0, 0x00, 0x00, 0xe0, 0x80, 0x00
, 0x00};
static const struct {
	NI cap;
	NIM_CHAR data[41];
} TM__kdeXVhLeMhTeIyOxnAjnxA_5 = {(40 | NIM_STRLIT_FLAG), "Malformed `if` statement in isAssignable"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_6 = {40, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_5))};
static const struct {
	NI cap;
	NIM_CHAR data[43];
} TM__kdeXVhLeMhTeIyOxnAjnxA_7 = {(42 | NIM_STRLIT_FLAG), "Malformed `case` statement in isAssignable"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_8 = {42, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_7))};
static const struct {
	NI cap;
	NIM_CHAR data[16];
} TM__kdeXVhLeMhTeIyOxnAjnxA_9 = {(15 | NIM_STRLIT_FLAG), "illformed AST: "};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_10 = {15, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_9))};
static const struct {
	NI cap;
	NIM_CHAR data[44];
} TM__kdeXVhLeMhTeIyOxnAjnxA_12 = {(43 | NIM_STRLIT_FLAG), "/home/blue/nimv2/compiler/parampatterns.nim"};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__kdeXVhLeMhTeIyOxnAjnxA_13 = {(1 | NIM_STRLIT_FLAG), "|"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_14 = {1, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_13))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__kdeXVhLeMhTeIyOxnAjnxA_15 = {(1 | NIM_STRLIT_FLAG), "&"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_16 = {1, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_15))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__kdeXVhLeMhTeIyOxnAjnxA_17 = {(1 | NIM_STRLIT_FLAG), "~"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_18 = {1, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_17))};
static const struct {
	NI cap;
	NIM_CHAR data[5];
} TM__kdeXVhLeMhTeIyOxnAjnxA_19 = {(4 | NIM_STRLIT_FLAG), "atom"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_20 = {4, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_19))};
static const struct {
	NI cap;
	NIM_CHAR data[4];
} TM__kdeXVhLeMhTeIyOxnAjnxA_21 = {(3 | NIM_STRLIT_FLAG), "lit"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_22 = {3, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_21))};
static const struct {
	NI cap;
	NIM_CHAR data[4];
} TM__kdeXVhLeMhTeIyOxnAjnxA_23 = {(3 | NIM_STRLIT_FLAG), "sym"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_24 = {3, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_23))};
static const struct {
	NI cap;
	NIM_CHAR data[6];
} TM__kdeXVhLeMhTeIyOxnAjnxA_25 = {(5 | NIM_STRLIT_FLAG), "ident"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_26 = {5, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_25))};
static const struct {
	NI cap;
	NIM_CHAR data[5];
} TM__kdeXVhLeMhTeIyOxnAjnxA_27 = {(4 | NIM_STRLIT_FLAG), "call"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_28 = {4, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_27))};
static const struct {
	NI cap;
	NIM_CHAR data[6];
} TM__kdeXVhLeMhTeIyOxnAjnxA_29 = {(5 | NIM_STRLIT_FLAG), "alias"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_30 = {5, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_29))};
static const struct {
	NI cap;
	NIM_CHAR data[8];
} TM__kdeXVhLeMhTeIyOxnAjnxA_31 = {(7 | NIM_STRLIT_FLAG), "noalias"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_32 = {7, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_31))};
static const struct {
	NI cap;
	NIM_CHAR data[7];
} TM__kdeXVhLeMhTeIyOxnAjnxA_33 = {(6 | NIM_STRLIT_FLAG), "lvalue"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_34 = {6, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_33))};
static const struct {
	NI cap;
	NIM_CHAR data[6];
} TM__kdeXVhLeMhTeIyOxnAjnxA_35 = {(5 | NIM_STRLIT_FLAG), "local"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_36 = {5, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_35))};
static const struct {
	NI cap;
	NIM_CHAR data[11];
} TM__kdeXVhLeMhTeIyOxnAjnxA_37 = {(10 | NIM_STRLIT_FLAG), "sideeffect"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_38 = {10, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_37))};
static const struct {
	NI cap;
	NIM_CHAR data[13];
} TM__kdeXVhLeMhTeIyOxnAjnxA_39 = {(12 | NIM_STRLIT_FLAG), "nosideeffect"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_40 = {12, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_39))};
static const struct {
	NI cap;
	NIM_CHAR data[1];
} TM__kdeXVhLeMhTeIyOxnAjnxA_41 = {(0 | NIM_STRLIT_FLAG), ""};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_42 = {0, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_41))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__kdeXVhLeMhTeIyOxnAjnxA_43 = {(1 | NIM_STRLIT_FLAG), "("};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_44 = {1, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_43))};
static const struct {
	NI cap;
	NIM_CHAR data[3];
} TM__kdeXVhLeMhTeIyOxnAjnxA_45 = {(2 | NIM_STRLIT_FLAG), ", "};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_46 = {2, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_45))};
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__kdeXVhLeMhTeIyOxnAjnxA_47 = {(1 | NIM_STRLIT_FLAG), ")"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_48 = {1, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_47))};
static const struct {
	NI cap;
	NIM_CHAR data[30];
} TM__kdeXVhLeMhTeIyOxnAjnxA_51 = {(29 | NIM_STRLIT_FLAG), "parameter pattern too complex"};
static const NimStringV2 TM__kdeXVhLeMhTeIyOxnAjnxA_52 = {29, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_51))};
static NIM_CONST tySet_tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw TM__kdeXVhLeMhTeIyOxnAjnxA_54 = {
0x10, 0xa9, 0x00, 0x00, 0x00, 0x60, 0x80, 0x00
, 0x00};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__kdeXVhLeMhTeIyOxnAjnxA_11 = {{43, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_12))}, ((NI) 48), ((NI) 12)};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__kdeXVhLeMhTeIyOxnAjnxA_49 = {{43, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_12))}, ((NI) 103), ((NI) 6)};
extern NIM_CONST tyObject_TLineInfo__NbXNNnBEIZ76UALAd0RnmQ unknownLineInfo__lineinfos_u361;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__kdeXVhLeMhTeIyOxnAjnxA_50 = {{43, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_12))}, ((NI) 110), ((NI) 6)};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__kdeXVhLeMhTeIyOxnAjnxA_53 = {{43, ((NimStrPayload*) (&TM__kdeXVhLeMhTeIyOxnAjnxA_12))}, ((NI) 130), ((NI) 19)};
extern NIM_BOOL nimInErrorMode__system_u4248;
static N_INLINE(NIM_BOOL, isAtom__ast_u7224)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NIM_BOOL result;
NIM_BOOL T1_;
T1_ = ((NIM_BOOL) 0);
T1_ = (((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0) <= (*n_p0).kind);
if ((!(T1_))) {
	goto LA2_;
}
T1_ = ((*n_p0).kind <= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 23));
LA2_: ;
result = T1_;
	return result;
}

static N_INLINE(NI, len__ast_u3191)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NI result;
NI T1_;
T1_ = (*n_p0)._kind_6.sons.len;
result = T1_;
	return result;
}

static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4248));
	return result;
}

static N_INLINE(NIM_BOOL, dontInlineConstant__trees_u396)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* orig_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* cnst_p1) {
	NIM_BOOL result;
NIM_BOOL T1_;
NI T3_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NIM_BOOL) 0);
T1_ = ((NIM_BOOL) 0);
T1_ = ((((((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 39)) || ((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 37))) || ((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 160))) || ((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 41))) || ((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 38)));
if ((!(T1_))) {
	goto LA2_;
}
T3_ = ((NI) 0);
T3_ = len__ast_u3191(cnst_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T1_ = (((*cnst_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 38)) < T3_);
LA2_: ;
result = T1_;
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(tyObject_TSym__28oQRSX37sWj59aavVTxbUA*, owner__ast_u6255)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_p0) {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
eqcopy___ast_u4578((&result), (*s_p0).ownerField);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg**, X5BX5D___ast_u5212)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** s_p0, NI s_p0Len_0, NI i_p1) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** result;
result = (&s_p0[((NI) (s_p0Len_0 - i_p1))]);
	return result;
}

static N_INLINE(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, lastSon__ast_u5209)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg** T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
T1_ = ((tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg**) 0);
T1_ = X5BX5D___ast_u5212((((*n_p0)._kind_6.sons).p ? ((*n_p0)._kind_6.sons).p->data : NIM_NIL), (*n_p0)._kind_6.sons.len, ((NI) 1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
eqcopy___ast_u3256((&result), (*T1_));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(NI, safeLen__ast_u3198)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NI result;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NI) 0);
{
	if ((!((((*n_p0).kind >= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0)) && ((*n_p0).kind <= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 23)))))) {
	goto LA3_;
}
result = ((NI) 0);
}
goto LA1_;
LA3_: ;
{
	result = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA1_: ;
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLentableBranch__parampatterns_u318)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* owner_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p1) {
	NIM_BOOL result;
tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NIM_BOOL) 0);
T1_ = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
T1_ = isAssignable__parampatterns_u315(owner_p0, n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
result = (((T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5)) || (T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4))) || (T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5)));
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg, isAssignable__parampatterns_u315)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* owner_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p1) {
	tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg result;
NIM_BOOL oldNimErrFin48_;
NIM_BOOL oldNimErrFin68_;
NIM_BOOL oldNimErrFin80_;
NIM_BOOL oldNimErrFin130_;
NIM_BOOL oldNimErrFin136_;
NIM_BOOL oldNimErrFin166_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
switch ((*n_p1).kind) {
case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 1):
	{
		{
	NIM_BOOL T4_;
T4_ = ((NIM_BOOL) 0);
T4_ = (!(((*n_p1).typField == ((tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*) NIM_NIL))));
if ((!(T4_))) {
	goto LA5_;
}
T4_ = ((*(*n_p1).typField).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23));
LA5_: ;
if ((!(T4_))) {
	goto LA6_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
LA6_: ;
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3):
	{
		tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD_;
colontmpD_ = NIM_NIL;
{
	tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg colontmpD__2;
tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg colontmpD__3;
if ((!(((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 3))))) {
	goto LA11_;
}
colontmpD__2 = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
colontmpD__3 = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
{
	if ((!((((*(*(*n_p1)._kind_4.sym).typ).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23)) || ((*(*(*n_p1)._kind_4.sym).typ).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 46)))))) {
	goto LA15_;
}
colontmpD__2 = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
result = colontmpD__2;
}
goto LA13_;
LA15_: ;
{
	colontmpD__3 = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4);
result = colontmpD__3;
}
LA13_: ;
}
goto LA9_;
LA11_: ;
{
	NIM_BOOL T19_;
T19_ = ((NIM_BOOL) 0);
T19_ = ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 10));
if ((!(T19_))) {
	goto LA20_;
}
colontmpD_ = astdef__ast_u4597((*n_p1)._kind_4.sym);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T19_ = dontInlineConstant__trees_u396(n_p1, colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
LA20_: ;
if ((!(T19_))) {
	goto LA21_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4);
}
goto LA9_;
LA21_: ;
{
	if ((!((((((((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 8)) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 11))) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 5))) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 3))) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 9))) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 21)))))) {
	goto LA24_;
}
{
	if ((!(((((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 3)) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 9))) || ((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 21)))))) {
	goto LA28_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4);
}
goto LA26_;
LA28_: ;
{
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* colontmpD__4;
colontmpD__4 = NIM_NIL;
{
	NIM_BOOL T33_;
NIM_BOOL T34_;
T33_ = ((NIM_BOOL) 0);
T34_ = ((NIM_BOOL) 0);
T34_ = (!((owner_p0 == ((tyObject_TSym__28oQRSX37sWj59aavVTxbUA*) NIM_NIL))));
if ((!(T34_))) {
	goto LA35_;
}
colontmpD__4 = owner__ast_u6255((*n_p1)._kind_4.sym);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T34_ = (owner_p0 == colontmpD__4);
LA35_: ;
T33_ = T34_;
if ((!(T33_))) {
	goto LA36_;
}
T33_ = (!((((*(*n_p1)._kind_4.sym).flags & (((NU64) 1) << (((NU) ((tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA) 3)) & 63U))) != 0)));
LA36_: ;
if ((!(T33_))) {
	goto LA37_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 2);
}
goto LA31_;
LA37_: ;
{
	result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
LA31_: ;
eqdestroy___ast_u4575(colontmpD__4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA26_: ;
}
goto LA9_;
LA24_: ;
{
	tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* t_1;
if ((!(((*(*n_p1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 7))))) {
	goto LA41_;
}
t_1 = NIM_NIL;
t_1 = skipTypes__ast_u5380((*(*n_p1)._kind_4.sym).typ, TM__kdeXVhLeMhTeIyOxnAjnxA_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	if ((!(((*t_1).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23))))) {
	goto LA45_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 6);
}
LA45_: ;
eqdestroy___ast_u3379(t_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
goto LA9_;
LA41_: ;
LA9_: ;
eqdestroy___ast_u3253(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 45):
	{
		tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* t_2;
t_2 = NIM_NIL;
t_2 = skipTypes__ast_u5380((*((*n_p1)._kind_6.sons).p->data[((NI) 0)]).typField, TM__kdeXVhLeMhTeIyOxnAjnxA_3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA48_;
}
{
	if ((!((((((*t_2).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23)) || ((*t_2).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 46))) || ((*t_2).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 21))) || ((*t_2).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 22)))))) {
	goto LA51_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
goto LA49_;
LA51_: ;
{
	if ((!(((*t_2).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 47))))) {
	goto LA54_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4);
}
goto LA49_;
LA54_: ;
{
	result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA48_;
}
}
LA49_: ;
{
	NIM_BOOL T59_;
NIM_BOOL T60_;
T59_ = ((NIM_BOOL) 0);
T60_ = ((NIM_BOOL) 0);
T60_ = (!((result == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0))));
if ((!(T60_))) {
	goto LA61_;
}
T60_ = ((*((*n_p1)._kind_6.sons).p->data[((NI) 1)]).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3));
LA61_: ;
T59_ = T60_;
if ((!(T59_))) {
	goto LA62_;
}
T59_ = (((*(*((*n_p1)._kind_6.sons).p->data[((NI) 1)])._kind_4.sym).flags & (((NU64) 1) << (((NU) ((tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA) 20)) & 63U))) != 0);
LA62_: ;
if ((!(T59_))) {
	goto LA63_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 3);
}
LA63_: ;
{
	LA48_: ;
}
{
	oldNimErrFin48_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3379(t_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin48_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 42):
	{
		tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* t_3;
t_3 = NIM_NIL;
t_3 = skipTypes__ast_u5380((*((*n_p1)._kind_6.sons).p->data[((NI) 0)]).typField, TM__kdeXVhLeMhTeIyOxnAjnxA_3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA68_;
}
{
	if ((!((((((*t_3).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23)) || ((*t_3).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 46))) || ((*t_3).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 21))) || ((*t_3).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 22)))))) {
	goto LA71_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
goto LA69_;
LA71_: ;
{
	if ((!(((*t_3).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 47))))) {
	goto LA74_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 4);
}
goto LA69_;
LA74_: ;
{
	result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA68_;
}
}
LA69_: ;
{
	LA68_: ;
}
{
	oldNimErrFin68_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3379(t_3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin68_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 58):
	case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 59):
		case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 60):
			{
				tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* colontmpD__5;
colontmpD__5 = NIM_NIL;
{
	colontmpD__5 = skipTypes__ast_u5380((*n_p1).typField, TM__kdeXVhLeMhTeIyOxnAjnxA_4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
if ((!(((((*colontmpD__5).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 27)) || ((*colontmpD__5).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 18))) || ((*colontmpD__5).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 17)))))) {
	goto LA83_;
}
result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
}
goto LA81_;
LA83_: ;
{
	NIM_BOOL T86_;
T86_ = ((NIM_BOOL) 0);
T86_ = compareTypes__types_u2778((*n_p1).typField, (*((*n_p1)._kind_6.sons).p->data[((NI) 1)]).typField, ((tyEnum_TDistinctCompare__HvUI0ZaOBLbYMykJoTLm7Q) 1), 1024);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
if ((!(T86_))) {
	goto LA87_;
}
result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
}
goto LA81_;
LA87_: ;
LA81_: ;
{
	LA80_: ;
}
{
	oldNimErrFin80_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3379(colontmpD__5);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin80_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
			break;
		
		case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 65):
			{
				tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n0_1;
n0_1 = NIM_NIL;
n0_1 = ((*n_p1)._kind_6.sons).p->data[((NI) 0)];
{
	if ((!(((*(*n0_1).typField).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 47))))) {
	goto LA94_;
}
{
	NIM_BOOL T98_;
T98_ = ((NIM_BOOL) 0);
T98_ = ((*n0_1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3));
if ((!(T98_))) {
	goto LA99_;
}
T98_ = ((*(*n0_1)._kind_4.sym).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 11));
LA99_: ;
if ((!(T98_))) {
	goto LA100_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
goto LA96_;
LA100_: ;
{
	result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5);
}
LA96_: ;
}
goto LA92_;
LA94_: ;
{
	result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
LA92_: ;
}
			break;
		
		case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 47):
			case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 64):
				{
					result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
				break;
			
			case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 67):
				case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 66):
					case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 46):
						{
							result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
						break;
					
					case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 26) ... ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 32):
						{
							tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ m_1;
m_1 = getMagic__trees_u122(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	if ((!((m_1 == ((tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ) 124))))) {
	goto LA109_;
}
{
	if ((!(((*(*((*n_p1)._kind_6.sons).p->data[((NI) 1)]).typField).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 21))))) {
	goto LA113_;
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
goto LA111_;
LA113_: ;
{
	result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA111_: ;
}
goto LA107_;
LA109_: ;
{
	if ((!((m_1 == ((tyEnum_TMagic__U1tSNTHXtU9aONpA756fhtQ) 5))))) {
	goto LA117_;
}
result = isAssignable__parampatterns_u315(owner_p0, ((*n_p1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
goto LA107_;
LA117_: ;
{
	if ((!((!(((*n_p1).typField == ((tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*) NIM_NIL))))))) {
	goto LA120_;
}
switch ((*(*n_p1).typField).kind) {
case ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23):
	{
		result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
	break;

case ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 47):
	{
		result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5);
}
	break;

default:
	{
	}
	break;

}
}
goto LA107_;
LA120_: ;
LA107_: ;
}
						break;
					
					case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 115):
						case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 126):
							{
								{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* colontmpD__6;
if ((!((!(((*n_p1).typField == ((tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*) NIM_NIL))))))) {
	goto LA128_;
}
colontmpD__6 = NIM_NIL;
colontmpD__6 = lastSon__ast_u5209(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA130_;
}
result = isAssignable__parampatterns_u315(owner_p0, colontmpD__6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA130_;
}
{
	LA130_: ;
}
{
	oldNimErrFin130_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3253(colontmpD__6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin130_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA128_: ;
}
							break;
						
						case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 143):
							{
								result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1);
}
							break;
						
						case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 48):
							case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 92):
								{
									{
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* branch_1;
branch_1 = NIM_NIL;
{
	NI i_1;
NI colontmp_;
NI i_2;
i_1 = ((NI) 0);
colontmp_ = ((NI) 0);
colontmp_ = safeLen__ast_u3198(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
i_2 = ((NI) 0);
{
	while (1) {
	if ((!((i_2 < colontmp_)))) {
	goto LA139;
}
i_1 = i_2;
eqcopy___ast_u3256((&branch_1), ((*n_p1)._kind_6.sons).p->data[i_1]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
{
	NI T142_;
T142_ = ((NI) 0);
T142_ = len__ast_u3191(branch_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
if ((!((T142_ == ((NI) 2))))) {
	goto LA143_;
}
{
	NIM_BOOL T147_;
T147_ = ((NIM_BOOL) 0);
T147_ = isLentableBranch__parampatterns_u318(owner_p0, ((*branch_1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
if ((!((!(T147_))))) {
	goto LA148_;
}
eqdestroy___ast_u3253(branch_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA148_: ;
}
goto LA140_;
LA143_: ;
{
	NI T151_;
T151_ = ((NI) 0);
T151_ = len__ast_u3191(branch_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
if ((!((T151_ == ((NI) 1))))) {
	goto LA152_;
}
{
	NIM_BOOL T156_;
T156_ = ((NIM_BOOL) 0);
T156_ = isLentableBranch__parampatterns_u318(owner_p0, ((*branch_1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
if ((!((!(T156_))))) {
	goto LA157_;
}
eqdestroy___ast_u3253(branch_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA157_: ;
}
goto LA140_;
LA152_: ;
{
	raiseAssert__stdZassertions_u10(TM__kdeXVhLeMhTeIyOxnAjnxA_6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA136_;
}
}
LA140_: ;
i_2 += ((NI) 1);
}
LA139: ;
}
}
{
	LA136_: ;
}
{
	oldNimErrFin136_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3253(branch_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin136_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5);
}
								break;
							
							case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 97):
								{
									{
	NI i_3;
NI colontmp__2;
NI i_4;
i_3 = ((NI) 0);
colontmp__2 = ((NI) 0);
colontmp__2 = len__ast_u3191(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
i_4 = ((NI) 1);
{
	while (1) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* branch_2;
if ((!((i_4 < colontmp__2)))) {
	goto LA165;
}
branch_2 = NIM_NIL;
i_3 = i_4;
eqcopy___ast_u3256((&branch_2), ((*n_p1)._kind_6.sons).p->data[i_3]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
switch ((*branch_2).kind) {
case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 85):
	{
		{
	NI T170_;
NIM_BOOL T171_;
T170_ = ((NI) 0);
T170_ = len__ast_u3191(branch_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
T171_ = ((NIM_BOOL) 0);
T171_ = isLentableBranch__parampatterns_u318(owner_p0, ((*branch_2)._kind_6.sons).p->data[((NI) (T170_ - ((NI) 1)))]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
if ((!((!(T171_))))) {
	goto LA172_;
}
eqdestroy___ast_u3253(branch_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA172_: ;
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 86):
	{
		{
	NIM_BOOL T177_;
T177_ = ((NIM_BOOL) 0);
T177_ = isLentableBranch__parampatterns_u318(owner_p0, ((*branch_2)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
if ((!((!(T177_))))) {
	goto LA178_;
}
eqdestroy___ast_u3253(branch_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA178_: ;
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 88):
	{
		{
	NIM_BOOL T183_;
T183_ = ((NIM_BOOL) 0);
T183_ = isLentableBranch__parampatterns_u318(owner_p0, ((*branch_2)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
if ((!((!(T183_))))) {
	goto LA184_;
}
eqdestroy___ast_u3253(branch_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA184_: ;
}
	break;

default:
	{
		raiseAssert__stdZassertions_u10(TM__kdeXVhLeMhTeIyOxnAjnxA_8);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA166_;
}
}
	break;

}
i_4 += ((NI) 1);
{
	LA166_: ;
}
{
	oldNimErrFin166_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3253(branch_2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin166_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA165: ;
}
}
result = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 5);
}
								break;
							
							default:
								{
								}
								break;
							
							}
						}
	BeforeRet_: ;
		return result;
}

static N_INLINE(NIM_BOOL, isRoutine__ast_u7153)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_p0) {
	NIM_BOOL result;
result = ((((((((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 12)) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 13))) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 18))) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 17))) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 15))) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 14))) || ((*s_p0).kind == ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 16)));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA, checkForSideEffects__parampatterns_u206)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA result;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0);
switch ((*n_p0).kind) {
case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 26) ... ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 32):
	{
		tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* op_1;
op_1 = NIM_NIL;
eqcopy___ast_u3256((&op_1), ((*n_p0)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
{
	NIM_BOOL T5_;
tyObject_TSym__28oQRSX37sWj59aavVTxbUA* s_1;
T5_ = ((NIM_BOOL) 0);
T5_ = ((*op_1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3));
if ((!(T5_))) {
	goto LA6_;
}
T5_ = isRoutine__ast_u7153((*op_1)._kind_4.sym);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
LA6_: ;
if ((!(T5_))) {
	goto LA7_;
}
s_1 = NIM_NIL;
s_1 = (*op_1)._kind_4.sym;
{
	if ((!((((*s_1).flags & (((NU64) 1) << (((NU) ((tyEnum_TSymFlag__5IlaLbJQ0rlzaqD4XpMwFA) 13)) & 63U))) != 0)))) {
	goto LA11_;
}
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1);
eqdestroy___ast_u3253(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
goto LA9_;
LA11_: ;
{
	if ((!((((*(*op_1).typField).flags & (((NU64) 1) << (((NU) ((tyEnum_TTypeFlag__UNcNxdTtVtYv5xD3A2Q9cKg) 1)) & 63U))) != 0)))) {
	goto LA14_;
}
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2);
}
goto LA9_;
LA14_: ;
{
	result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1);
}
LA9_: ;
}
goto LA3_;
LA7_: ;
{
	if ((!((((*(*op_1).typField).flags & (((NU64) 1) << (((NU) ((tyEnum_TTypeFlag__UNcNxdTtVtYv5xD3A2Q9cKg) 1)) & 63U))) != 0)))) {
	goto LA18_;
}
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2);
}
goto LA3_;
LA18_: ;
{
	result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1);
eqdestroy___ast_u3253(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA3_: ;
{
	NI i_1;
NI colontmp_;
NI i_2;
i_1 = ((NI) 0);
colontmp_ = ((NI) 0);
colontmp_ = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
i_2 = ((NI) 0);
{
	while (1) {
	tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA ret_1;
if ((!((i_2 < colontmp_)))) {
	goto LA23;
}
i_1 = i_2;
ret_1 = checkForSideEffects__parampatterns_u206(((*n_p0)._kind_6.sons).p->data[i_1]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
{
	if ((!((ret_1 == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1))))) {
	goto LA26_;
}
result = ret_1;
eqdestroy___ast_u3253(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
goto LA24_;
LA26_: ;
{
	NIM_BOOL T29_;
T29_ = ((NIM_BOOL) 0);
T29_ = (ret_1 == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0));
if ((!(T29_))) {
	goto LA30_;
}
T29_ = (result == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2));
LA30_: ;
if ((!(T29_))) {
	goto LA31_;
}
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0);
}
goto LA24_;
LA31_: ;
LA24_: ;
i_2 += ((NI) 1);
}
LA23: ;
}
}
{
	LA2_: ;
}
{
	oldNimErrFin2_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3253(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin2_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0) ... ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 23):
	{
		result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2);
}
	break;

default:
	{
		result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2);
{
	NI i_3;
NI colontmp__2;
NI i_4;
i_3 = ((NI) 0);
colontmp__2 = ((NI) 0);
colontmp__2 = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
i_4 = ((NI) 0);
{
	while (1) {
	tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA ret_2;
if ((!((i_4 < colontmp__2)))) {
	goto LA39;
}
i_3 = i_4;
ret_2 = checkForSideEffects__parampatterns_u206(((*n_p0)._kind_6.sons).p->data[i_3]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
{
	if ((!((ret_2 == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1))))) {
	goto LA42_;
}
result = ret_2;
goto BeforeRet_;
}
goto LA40_;
LA42_: ;
{
	NIM_BOOL T45_;
T45_ = ((NIM_BOOL) 0);
T45_ = (ret_2 == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0));
if ((!(T45_))) {
	goto LA46_;
}
T45_ = (result == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 2));
LA46_: ;
if ((!(T45_))) {
	goto LA47_;
}
result = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0);
}
goto LA40_;
LA47_: ;
LA40_: ;
i_4 += ((NI) 1);
}
LA39: ;
}
}
}
	break;

}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, matchNodeKinds__parampatterns_u498)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* p_p0, tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p1) {
	NIM_BOOL result;
NimStringV2 code_1;
tyArray__zl3qUQvo0CT9bJi9b5H7mRkw stack_1;
NI sp_1;
NI pc_1;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NIM_BOOL) 0);
code_1.len = 0;
code_1.p = NIM_NIL;
stack_1[(((NI) 0) - 0)] = NIM_TRUE;
sp_1 = ((NI) 1);
code_1 = (*p_p0)._kind_3.strVal;
pc_1 = ((NI) 1);
{
	while (1) {
	switch (((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) (((NU8) (code_1).p->data[pc_1])))) {
case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 1):
	{
		goto LA1;
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 2):
	{
		NIM_BOOL T5_;
T5_ = ((NIM_BOOL) 0);
T5_ = stack_1[(((NI) (sp_1 - ((NI) 1))) - 0)];
if (T5_) {
	goto LA6_;
}
T5_ = stack_1[(((NI) (sp_1 - ((NI) 2))) - 0)];
LA6_: ;
stack_1[(((NI) (sp_1 - ((NI) 2))) - 0)] = T5_;
sp_1 -= ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 3):
	{
		NIM_BOOL T8_;
T8_ = ((NIM_BOOL) 0);
T8_ = stack_1[(((NI) (sp_1 - ((NI) 1))) - 0)];
if ((!(T8_))) {
	goto LA9_;
}
T8_ = stack_1[(((NI) (sp_1 - ((NI) 2))) - 0)];
LA9_: ;
stack_1[(((NI) (sp_1 - ((NI) 2))) - 0)] = T8_;
sp_1 -= ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 4):
	{
		stack_1[(((NI) (sp_1 - ((NI) 1))) - 0)] = (!(stack_1[(((NI) (sp_1 - ((NI) 1))) - 0)]));
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 5):
	{
		stack_1[(sp_1 - 0)] = ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 6):
	{
		NIM_BOOL T13_;
T13_ = ((NIM_BOOL) 0);
T13_ = isAtom__ast_u7224(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
stack_1[(sp_1 - 0)] = T13_;
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 7):
	{
		stack_1[(sp_1 - 0)] = (((*n_p1).kind >= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 5)) && ((*n_p1).kind <= ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 23)));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 8):
	{
		stack_1[(sp_1 - 0)] = ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 2));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 9):
	{
		stack_1[(sp_1 - 0)] = ((((((((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 27)) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 29))) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 30))) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 31))) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 26))) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 28))) || ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 32)));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 10):
	{
		tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA kind_1;
NIM_BOOL T18_;
kind_1 = ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) (((NU8) (code_1).p->data[((NI) (pc_1 + ((NI) 1)))])));
T18_ = ((NIM_BOOL) 0);
T18_ = ((*n_p1).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3));
if ((!(T18_))) {
	goto LA19_;
}
T18_ = ((*(*n_p1)._kind_4.sym).kind == kind_1);
LA19_: ;
stack_1[(sp_1 - 0)] = T18_;
sp_1 += ((NI) 1);
pc_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 11):
	{
		tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ kind_2;
kind_2 = ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) (((NU8) (code_1).p->data[((NI) (pc_1 + ((NI) 1)))])));
stack_1[(sp_1 - 0)] = ((*n_p1).kind == kind_2);
sp_1 += ((NI) 1);
pc_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 12):
	{
		tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg T22_;
T22_ = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
T22_ = isAssignable__parampatterns_u315(((tyObject_TSym__28oQRSX37sWj59aavVTxbUA*) NIM_NIL), n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
stack_1[(sp_1 - 0)] = ((T22_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1)) || (T22_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 2)));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 13):
	{
		tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg T24_;
T24_ = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
T24_ = isAssignable__parampatterns_u315(((tyObject_TSym__28oQRSX37sWj59aavVTxbUA*) NIM_NIL), n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
stack_1[(sp_1 - 0)] = (T24_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 2));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 14):
	{
		tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA T26_;
T26_ = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0);
T26_ = checkForSideEffects__parampatterns_u206(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
stack_1[(sp_1 - 0)] = (T26_ == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1));
sp_1 += ((NI) 1);
}
	break;

case ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 15):
	{
		tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA T28_;
T28_ = ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 0);
T28_ = checkForSideEffects__parampatterns_u206(n_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
stack_1[(sp_1 - 0)] = (!((T28_ == ((tyEnum_TSideEffectAnalysis__epVlm9bt9bVy7V8lILQ6nCxA) 1))));
sp_1 += ((NI) 1);
}
	break;

default:
	__builtin_unreachable();

}
pc_1 += ((NI) 1);
}
}
LA1: ;
result = stack_1[(((NI) (sp_1 - ((NI) 1))) - 0)];
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI) 1));
(*(*s_p0).p).data[(*s_p0).len] = c_p1;
(*s_p0).len += ((NI) 1);
(*(*s_p0).p).data[(*s_p0).len] = 0;
}

static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}

static N_INLINE(void, copyMem__system_u1724)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}

static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
	if ((!((((NI) 0) < src_p1.len)))) {
	goto LA3_;
}
copyMem__system_u1724(((void*) (((&(*(*dest_p0).p).data[(*dest_p0).len])))), ((void*) (((&(*src_p1.p).data[((NI) 0)])))), (src_p1.len));
(*dest_p0).len += src_p1.len;
(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, patternError__parampatterns_u39)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p1) {
	NimStringV2 colontmpD_;
NimStringV2 colontmpD__2;
NimStringV2 T2_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
T2_.len = 0;
T2_.p = NIM_NIL;
colontmpD_ = renderTree__renderer_u59(n_p0, 4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
T2_ = rawNewString((15 + colontmpD_.len));
appendString(((&T2_)), TM__kdeXVhLeMhTeIyOxnAjnxA_10);
appendString(((&T2_)), colontmpD_);
colontmpD__2 = T2_;
liMessage__msgs_u1223(conf_p1, (*n_p0).info, ((tyEnum_TMsgKind__iz4UvM3kK9cv7Vr9cxzAlIGw) 17), colontmpD__2, ((tyEnum_TErrorHandling__muRdtwJRTgC0pLAbV2ARkA) 0), ((&TM__kdeXVhLeMhTeIyOxnAjnxA_11)), NIM_FALSE, NIM_FALSE);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	LA1_: ;
}
{
	eqdestroy___system_u2624(colontmpD__2);
eqdestroy___system_u2624(colontmpD_);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem__system_u1732)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
int T1_;
T1_ = ((int) 0);
T1_ = nimCmpMem(a_p0, b_p1, size_p2);
result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
NI alen_1;
NI blen_1;
{
		result = NIM_FALSE;
alen_1 = a_p0.len;
blen_1 = b_p1.len;
{
	if ((!((alen_1 == blen_1)))) {
	goto LA3_;
}
{
	if ((!((alen_1 == ((NI) 0))))) {
	goto LA7_;
}
result = NIM_TRUE;
goto BeforeRet_;
}
LA7_: ;
result = equalMem__system_u1732(((void*) (((&(a_p0).p->data[((NI) 0)])))), ((void*) (((&(b_p1).p->data[((NI) 0)])))), (alen_1));
goto BeforeRet_;
}
LA3_: ;
}
	BeforeRet_: ;
		return result;
}

static N_INLINE(void, add__parampatterns_u42)(NimStringV2* code_p0, tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA op_p1) {
	nimAddCharV1(((&(*code_p0))), ((NIM_CHAR) ((op_p1))));
}

static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = (!(((*s_p0).p == ((NimStrPayload*) NIM_NIL))));
if ((!(T3_))) {
	goto LA4_;
}
T3_ = (((NI) ((*(*s_p0).p).cap & ((NI) IL64(4611686018427387904)))) == ((NI) IL64(4611686018427387904)));
LA4_: ;
if ((!(T3_))) {
	goto LA5_;
}
nimPrepareStrMutationImpl__system_u2373(s_p0);
}
LA5_: ;
}

static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
}

static N_INLINE(NimStringV2, toFileLineCol__msgs_u701)(tyTuple__kN8up2W6YKc5YA9avn5mV5w* info_p0) {
	NimStringV2 result;
result = TM__kdeXVhLeMhTeIyOxnAjnxA_42;
prepareAdd(((&result)), (0 + (*info_p0).Field0.len));
appendString(((&result)), (*info_p0).Field0);
{
	if ((!((((NI) 0) < (*info_p0).Field1)))) {
	goto LA3_;
}
prepareAdd(((&result)), 1);
appendString(((&result)), TM__kdeXVhLeMhTeIyOxnAjnxA_44);
addInt__stdZprivateZdigitsutils_u204(((&result)), (*info_p0).Field1);
{
	if ((!((((NI) 0) < ((NI) ((*info_p0).Field2 + ((NI) 1))))))) {
	goto LA7_;
}
prepareAdd(((&result)), 2);
appendString(((&result)), TM__kdeXVhLeMhTeIyOxnAjnxA_46);
addInt__stdZprivateZdigitsutils_u204(((&result)), ((NI) ((*info_p0).Field2 + ((NI) 1))));
}
LA7_: ;
prepareAdd(((&result)), 1);
appendString(((&result)), TM__kdeXVhLeMhTeIyOxnAjnxA_48);
}
LA3_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, compileConstraints__parampatterns_u78)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* p_p0, NimStringV2* result_p1, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p2) {
	NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
switch ((*p_p0).kind) {
case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 26) ... ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 32):
	{
		tyObject_TIdent__un9ccjtt539bmsw80XV2co0w* op_1;
op_1 = NIM_NIL;
{
	if ((!((!(((*((*p_p0)._kind_6.sons).p->data[((NI) 0)]).kind == ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 2))))))) {
	goto LA5_;
}
patternError__parampatterns_u39(((*p_p0)._kind_6.sons).p->data[((NI) 0)], conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
eqdestroy___idents_u155(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
LA5_: ;
eqcopy___idents_u158((&op_1), (*((*p_p0)._kind_6.sons).p->data[((NI) 0)])._kind_5.ident);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
{
	NI T9_;
T9_ = ((NI) 0);
T9_ = len__ast_u3191(p_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
if ((!((T9_ == ((NI) 3))))) {
	goto LA10_;
}
{
	NIM_BOOL T14_;
T14_ = ((NIM_BOOL) 0);
T14_ = eqStrings((*op_1).s, TM__kdeXVhLeMhTeIyOxnAjnxA_14);
if (T14_) {
	goto LA15_;
}
T14_ = ((*op_1).id == ((NI) 47));
LA15_: ;
if ((!(T14_))) {
	goto LA16_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 1)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 2)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 2));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
}
goto LA12_;
LA16_: ;
{
	NIM_BOOL T19_;
T19_ = ((NIM_BOOL) 0);
T19_ = eqStrings((*op_1).s, TM__kdeXVhLeMhTeIyOxnAjnxA_16);
if (T19_) {
	goto LA20_;
}
T19_ = ((*op_1).id == ((NI) 2));
LA20_: ;
if ((!(T19_))) {
	goto LA21_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 1)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 2)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 3));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
}
goto LA12_;
LA21_: ;
{
	patternError__parampatterns_u39(p_p0, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
}
LA12_: ;
}
goto LA7_;
LA10_: ;
{
	NIM_BOOL T25_;
NI T26_;
NIM_BOOL T28_;
T25_ = ((NIM_BOOL) 0);
T26_ = ((NI) 0);
T26_ = len__ast_u3191(p_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
T25_ = (T26_ == ((NI) 2));
if ((!(T25_))) {
	goto LA27_;
}
T28_ = ((NIM_BOOL) 0);
T28_ = eqStrings((*op_1).s, TM__kdeXVhLeMhTeIyOxnAjnxA_18);
if (T28_) {
	goto LA29_;
}
T28_ = ((*op_1).id == ((NI) 43));
LA29_: ;
T25_ = T28_;
LA27_: ;
if ((!(T25_))) {
	goto LA30_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 1)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 4));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
}
goto LA7_;
LA30_: ;
{
	patternError__parampatterns_u39(p_p0, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA2_;
}
}
LA7_: ;
{
	LA2_: ;
}
{
	oldNimErrFin2_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___idents_u155(op_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin2_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 53):
	case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 37):
		{
			{
	NI T38_;
T38_ = ((NI) 0);
T38_ = len__ast_u3191(p_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!((T38_ == ((NI) 1))))) {
	goto LA39_;
}
compileConstraints__parampatterns_u78(((*p_p0)._kind_6.sons).p->data[((NI) 0)], result_p1, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
goto LA36_;
LA39_: ;
{
	patternError__parampatterns_u39(p_p0, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA36_: ;
}
		break;
	
	case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 2):
		{
			NimStringV2 spec_1;
spec_1.len = 0;
spec_1.p = NIM_NIL;
spec_1 = nsuNormalize((*(*p_p0)._kind_5.ident).s);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
switch ((hashString(spec_1) & 15)) {
case 2:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_40)) {
	goto LA54_;
}
break;

case 4:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_24)) {
	goto LA46_;
}
if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_34)) {
	goto LA51_;
}
if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_38)) {
	goto LA53_;
}
break;

case 6:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_26)) {
	goto LA47_;
}
break;

case 10:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_32)) {
	goto LA50_;
}
break;

case 11:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_20)) {
	goto LA44_;
}
break;

case 12:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_22)) {
	goto LA45_;
}
break;

case 13:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_28)) {
	goto LA48_;
}
break;

case 14:
	if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_30)) {
	goto LA49_;
}
if (eqStrings(spec_1, TM__kdeXVhLeMhTeIyOxnAjnxA_36)) {
	goto LA52_;
}
break;

}
goto LA55_;
LA44_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 6));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA45_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 7));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA46_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 5));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA47_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 8));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA48_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 9));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA49_: ;
{
	nimPrepareStrMutationV2(((&(*result_p1))));
((*result_p1)).p->data[((NI) 0)] = 2;
}
goto LA56_;
LA50_: ;
{
	nimPrepareStrMutationV2(((&(*result_p1))));
((*result_p1)).p->data[((NI) 0)] = 3;
}
goto LA56_;
LA51_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 12));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA52_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 13));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA53_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 14));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA54_: ;
{
	add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 15));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
goto LA56_;
LA55_: ;
{
	{
	NimStringV2 argX60gensym13__1;
if ((!(NIM_FALSE))) {
	goto LA71_;
}
argX60gensym13__1.len = 0;
argX60gensym13__1.p = NIM_NIL;
argX60gensym13__1 = toFileLineCol__msgs_u701(((&TM__kdeXVhLeMhTeIyOxnAjnxA_49)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA73_;
}
internalErrorImpl__msgs_u1594(conf_p2, unknownLineInfo__lineinfos_u361, argX60gensym13__1, ((&TM__kdeXVhLeMhTeIyOxnAjnxA_49)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA73_;
}
{
	LA73_: ;
}
{
	eqdestroy___system_u2624(argX60gensym13__1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
LA71_: ;
{
	tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA i_1;
i_1 = ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 0);
{
	tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA v_1;
NI res_1;
v_1 = ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) 0);
res_1 = ((NI) 0);
{
	while (1) {
	NimStringV2 colontmpD_;
if ((!((res_1 <= ((NI) 24))))) {
	goto LA79;
}
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
v_1 = ((tyEnum_TSymKind__2Al6h2IlqYxDcO2tpbV2nA) (res_1));
i_1 = v_1;
{
	NI T83_;
colontmpD_ = toHumanStr__ast_u7575(i_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
T83_ = ((NI) 0);
T83_ = nsuCmpIgnoreStyle(colontmpD_, spec_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
if ((!((T83_ == ((NI) 0))))) {
	goto LA84_;
}
add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 10));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA80_;
}
nimAddCharV1(((&(*result_p1))), ((NIM_CHAR) ((i_1))));
eqdestroy___system_u2624(colontmpD_);
eqdestroy___system_u2624(spec_1);
goto BeforeRet_;
}
LA84_: ;
res_1 += ((NI) 1);
{
	LA80_: ;
}
{
	eqdestroy___system_u2624(colontmpD_);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
LA79: ;
}
}
}
{
	NimStringV2 argX60gensym15__1;
if ((!(NIM_FALSE))) {
	goto LA90_;
}
argX60gensym15__1.len = 0;
argX60gensym15__1.p = NIM_NIL;
argX60gensym15__1 = toFileLineCol__msgs_u701(((&TM__kdeXVhLeMhTeIyOxnAjnxA_50)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA92_;
}
internalErrorImpl__msgs_u1594(conf_p2, unknownLineInfo__lineinfos_u361, argX60gensym15__1, ((&TM__kdeXVhLeMhTeIyOxnAjnxA_50)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA92_;
}
{
	LA92_: ;
}
{
	eqdestroy___system_u2624(argX60gensym15__1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
LA90_: ;
{
	tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ i_2;
i_2 = ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0);
{
	tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ v_2;
NI res_2;
v_2 = ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 0);
res_2 = ((NI) 0);
{
	while (1) {
	NimStringV2 colontmpD__2;
if ((!((res_2 <= ((NI) 165))))) {
	goto LA98;
}
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
v_2 = ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) (res_2));
i_2 = v_2;
{
	NI T102_;
colontmpD__2 = dollar___nodekinds_u168(i_2);
T102_ = ((NI) 0);
T102_ = nsuCmpIgnoreStyle(colontmpD__2, spec_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA99_;
}
if ((!((T102_ == ((NI) 0))))) {
	goto LA103_;
}
add__parampatterns_u42(result_p1, ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 11));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA99_;
}
nimAddCharV1(((&(*result_p1))), ((NIM_CHAR) ((i_2))));
eqdestroy___system_u2624(colontmpD__2);
eqdestroy___system_u2624(spec_1);
goto BeforeRet_;
}
LA103_: ;
res_2 += ((NI) 1);
{
	LA99_: ;
}
{
	eqdestroy___system_u2624(colontmpD__2);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
LA98: ;
}
}
}
patternError__parampatterns_u39(p_p0, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA43_;
}
}
LA56_: ;
{
	LA43_: ;
}
{
	eqdestroy___system_u2624(spec_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
		break;
	
	default:
		{
			patternError__parampatterns_u39(p_p0, conf_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
		break;
	
	}
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*, semNodeKindConstraints__parampatterns_u180)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, tyObject_ConfigRefcolonObjectType___KWeA8o66bVo7uX0cQIugmQ* conf_p1, NI start_p2) {
	tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* result;
NimStringV2 T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
result = newNodeI__ast_u4092(((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 20), (*n_p0).info);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
T1_.len = 0;
T1_.p = NIM_NIL;
T1_ = rawNewString(((NI) 10));
eqsink___system_u2633(((&(*result)._kind_3.strVal)), T1_);
nimAddCharV1(((&(*result)._kind_3.strVal)), 1);
{
	NI T4_;
T4_ = ((NI) 0);
T4_ = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!((((NI) 2) <= T4_)))) {
	goto LA5_;
}
{
	NI i_1;
NI colontmp_;
NI T8_;
NI i_2;
i_1 = ((NI) 0);
colontmp_ = ((NI) 0);
T8_ = ((NI) 0);
T8_ = len__ast_u3191(n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
colontmp_ = (T8_);
i_2 = start_p2;
{
	while (1) {
	if ((!((i_2 < colontmp_)))) {
	goto LA10;
}
i_1 = i_2;
compileConstraints__parampatterns_u78(((*n_p0)._kind_6.sons).p->data[i_1], ((&(*result)._kind_3.strVal)), conf_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
i_2 += ((NI) 1);
}
LA10: ;
}
}
{
	if ((!((((NI) 63) < (*result)._kind_3.strVal.len)))) {
	goto LA13_;
}
internalErrorImpl__msgs_u1594(conf_p1, (*n_p0).info, TM__kdeXVhLeMhTeIyOxnAjnxA_52, ((&TM__kdeXVhLeMhTeIyOxnAjnxA_53)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA13_: ;
}
goto LA2_;
LA5_: ;
{
	patternError__parampatterns_u39(n_p0, conf_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA2_: ;
add__parampatterns_u42(((&(*result)._kind_3.strVal)), ((tyEnum_TOpcode__mmuBK9c9cVRnd9bEpxmeFt5RA) 1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw, whichAlias__parampatterns_u49)(tyObject_TSym__28oQRSX37sWj59aavVTxbUA* p_p0) {
	tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw result;
result = ((tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw) 0);
{
	if ((!((!(((*p_p0).constraint == ((tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg*) NIM_NIL))))))) {
	goto LA3_;
}
result = ((tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw) (((NU8) ((*(*p_p0).constraint)._kind_3.strVal).p->data[((NI) 0)])));
}
goto LA1_;
LA3_: ;
{
	result = ((tyEnum_TAliasRequest__n2MMwt5Y2eMstPxEpBKykw) 1);
}
LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__28oQRSX37sWj59aavVTxbUA*, exprRoot__parampatterns_u294)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0, NIM_BOOL allowCalls_p1) {
	tyObject_TSym__28oQRSX37sWj59aavVTxbUA* result;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* it_1;
NIM_BOOL oldNimErrFin6_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = NIM_NIL;
it_1 = NIM_NIL;
result = ((tyObject_TSym__28oQRSX37sWj59aavVTxbUA*) NIM_NIL);
eqcopy___ast_u3256((&it_1), n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	while (1) {
	switch ((*it_1).kind) {
case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 3):
	{
		eqcopy___ast_u4578((&result), (*it_1)._kind_4.sym);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
eqdestroy___ast_u3253(it_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
goto BeforeRet_;
}
	break;

case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 65):
	case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 47):
		{
			tyObject_TType__ovu87YsUa1ANGt6vVxQTnw* colontmpD_;
colontmpD_ = NIM_NIL;
{
	colontmpD_ = skipTypes__ast_u5380((*((*it_1)._kind_6.sons).p->data[((NI) 0)]).typField, TM__kdeXVhLeMhTeIyOxnAjnxA_54);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
if ((!((((*colontmpD_).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 21)) || ((*colontmpD_).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 22)))))) {
	goto LA9_;
}
eqdestroy___ast_u3379(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
goto LA2;
}
goto LA7_;
LA9_: ;
{
	eqcopy___ast_u3256((&it_1), ((*it_1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA6_;
}
}
LA7_: ;
{
	LA6_: ;
}
{
	oldNimErrFin6_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3379(colontmpD_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
(*nimErr_) = oldNimErrFin6_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
		break;
	
	case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 45):
		case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 42):
			case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 64):
				case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 67):
					case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 66):
						case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 46):
							{
								eqcopy___ast_u3256((&it_1), ((*it_1)._kind_6.sons).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
							break;
						
						case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 58):
							case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 59):
								case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 60):
									{
										eqcopy___ast_u3256((&it_1), ((*it_1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
									break;
								
								case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 115):
									case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 126):
										{
											{
	NIM_BOOL T19_;
NI T20_;
tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* T24_;
T19_ = ((NIM_BOOL) 0);
T20_ = ((NI) 0);
T20_ = len__ast_u3191(it_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
T19_ = (((NI) 0) < T20_);
if ((!(T19_))) {
	goto LA21_;
}
T19_ = (!(((*it_1).typField == ((tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*) NIM_NIL))));
LA21_: ;
if ((!(T19_))) {
	goto LA22_;
}
T24_ = NIM_NIL;
T24_ = lastSon__ast_u5209(it_1);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___ast_u3253(T24_);
	goto LA1_;
}
eqsink___ast_u3262((&it_1), T24_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
goto LA17_;
LA22_: ;
{
	goto LA2;
}
LA17_: ;
}
										break;
									
									case ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 26) ... ((tyEnum_TNodeKind__7uLZ8K9bmfF1GZOQC457StQ) 32):
										{
											{
	NIM_BOOL T29_;
NIM_BOOL T30_;
NIM_BOOL T31_;
NI T35_;
T29_ = ((NIM_BOOL) 0);
T30_ = ((NIM_BOOL) 0);
T31_ = ((NIM_BOOL) 0);
T31_ = allowCalls_p1;
if ((!(T31_))) {
	goto LA32_;
}
T31_ = (!(((*it_1).typField == ((tyObject_TType__ovu87YsUa1ANGt6vVxQTnw*) NIM_NIL))));
LA32_: ;
T30_ = T31_;
if ((!(T30_))) {
	goto LA33_;
}
T30_ = (((*(*it_1).typField).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 23)) || ((*(*it_1).typField).kind == ((tyEnum_TTypeKind__Uklpw0ZRY1nkymLqpRDwgw) 47)));
LA33_: ;
T29_ = T30_;
if ((!(T29_))) {
	goto LA34_;
}
T35_ = ((NI) 0);
T35_ = len__ast_u3191(it_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
T29_ = (((NI) 1) < T35_);
LA34_: ;
if ((!(T29_))) {
	goto LA36_;
}
eqcopy___ast_u3256((&it_1), ((*it_1)._kind_6.sons).p->data[((NI) 1)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
goto LA27_;
LA36_: ;
{
	goto LA2;
}
LA27_: ;
}
										break;
									
									default:
										{
											goto LA2;
}
										break;
									
									}
								}
}
LA2: ;
{
	LA1_: ;
}
{
	oldNimErrFin1_ = (*nimErr_);
(*nimErr_) = NIM_FALSE;
eqdestroy___ast_u3253(it_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
(*nimErr_) = oldNimErrFin1_;
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLValue__parampatterns_u491)(tyObject_TNode__FbBYfERj9cP0YMBw9cPxu9bQg* n_p0) {
	NIM_BOOL result;
tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg T1_;
NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
result = ((NIM_BOOL) 0);
T1_ = ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 0);
T1_ = isAssignable__parampatterns_u315(((tyObject_TSym__28oQRSX37sWj59aavVTxbUA*) NIM_NIL), n_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
result = (((T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 1)) || (T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 2))) || (T1_ == ((tyEnum_TAssignableResult__FG7n9aAufik29bnIpjhniqYg) 6)));
}
	BeforeRet_: ;
		return result;
}

